### ISSUE TITLE
How to do model based testing?

### ISSUE THREAD

**Issue by forki** [fscheck/FsCheck#107]
i came across John Hughes' excellent video from https://vimeo.com/68383317 and tried to reimplement his first sample. It's similar to https://fscheck.github.io/FsCheck/StatefulTesting.html but a little bit more complicated. This is the class I want to test:

    type Queue<'a>(bufferSize:int) =
        let mutable input = 0
        let mutable output = 0
        let buffer : 'a[] = Array.zeroCreate bufferSize

        member __.Put x = 
            buffer.[input] <- x
            input <- (input + 1) % bufferSize

        member __.Get() = 
            let x = buffer.[output]
            output <- (output + 1) % bufferSize
            x

        member __.Size() = (input - output) % bufferSize

Now I tried to define the model:

    let spec =
      let put testElement =
          { new Command<Queue<int>,_>() with
              member x.RunActual c =  c.Put testElement; c
              member x.RunModel m = m @ [testElement]
              member x.Post (c,m) = List.head m = c.Get() |> Prop.ofTestable // calling Get??
              override x.ToString() = "put"}

      let get = 
          { new Command<Queue<int>,_>() with
              member x.RunActual c = c.Get(); c
              member x.RunModel m = List.tail m
              member x.Post (c,m) =  List.head m = c.Get() |> Prop.ofTestable // calling Get twice??
              override x.ToString() = "get"}

      { new ICommandGenerator<Queue<int>,_> with
          member __.InitialActual = Queue(1) /// n??
          member __.InitialModel = []
          member __.Next model = Gen.elements [put (*random element *) ;get] }

    Check.Quick (Command.toProperty spec)

But this fails for a couple of reasons. 

1) If I understand the video at 10min correctly the RunActual function should capture the method result and the new `Actual`. This would allow me to specify the correct post condition.

2) how can I generate operations that put random elements?

3) how can I generate queues with random buffer sizes?

**Comment by kurtschelfthout** [comment]
1. Yes, the output of RunActual is currently not available in Post, but it makes sense to add that. You can of course add a pure c.Peek to your class and use that instead of Get. Clearly post conditions should not have any side effects.

2. Something like the below should get you started (untested!):

```
let putGen = gen { let! elem = Arb.generate<int>
                   return put elem }
Gen.oneOf [ putGen; Gen.constant get ]
```

3. Interesting - you can't currently because the InitialActual takes a value, not a generator. I figured a generator doesn't make sense, because you want to match with a model, but of course the actual can have parameters that don't have any effect on the model, such as initial capacity and so on.

**Comment by forki** [comment]
1) c.Peek means I would change the API of the class under test. this is not possible in every case.

2) will try

3) so are you going to change that?

**Comment by kurtschelfthout** [comment]
Yeah, I'll change 1 and 3.

**Comment by kurtschelfthout** [comment]
This rabbit hole is turning out to be deeper than I thought. I've essentially started rewriting the thing. And found some awesome bugs in the process. So currently I think I'll release some of the bugfixes I can backport in a maintenance release, then do a bigger release with the re-worked Commands module - much closer to  Erlang QuickCheck.

**Comment by forki** [comment]
Very cool

**Comment by kurtschelfthout** [comment]
By the way, follow progress on https://github.com/fscheck/FsCheck/tree/commands-revamp

I've got shrinking sort of working locally, will push soon. But you can comment on the API a bit. Notice I collapsed PostCondition and RunActual to one Check method - so that you can access the result of the method you're invoking directly in the property. Also you can generate the initial object.

**Comment by kurtschelfthout** [comment]
It's now in FsCheck.Experimental.StateMachine on master. I plan to keep it there for a bit until it's more finished, then deprecate the old Commands. But it's already usable, if you want to have a play. 

https://github.com/fscheck/FsCheck/blob/master/src/FsCheck/StateMachine.fs

**Comment by kurtschelfthout** [comment]
I now wrote some docs on the new thing: https://fscheck.github.io/FsCheck/StatefulTestingNew.html

I'm going to close this issue as this should address the three points you mentioned; however feel free to open new issues if you end up trying it and run into other problems.

**Comment by mmcedora** [comment]
@kurtschelfthout Is this still experimental or safe to use?
