### ISSUE TITLE
Support Portable Class Library profiles 7/78/259/47

### ISSUE THREAD

**Issue by kurtschelfthout** [fscheck/FsCheck#110]
So that FsCheck tests can be more easily integrated with FSharp.Core tests written by the inimitable @forki in this [epic PR](https://github.com/Microsoft/visualfsharp/pull/502).

@latkin [explained](https://github.com/Microsoft/visualfsharp/pull/502#issuecomment-118209347) we need to support profiles 47, 7, 259, and 78, and mostly the three latter.

I've been tentatively looking at the code changes necessary and they seem very doable.

Don't have much experience with PCL though, so not sure what this means for the NuGet package - I would assume that since we currently target .NET4.5, it would be a non-breaking change to release a package for 7/78/259? @mausch  or @ploeh any experience here?

As a reference: http://embed.plnkr.co/03ck2dCtnJogBKHJ9EjY/preview

Profile | nuget moniker
---------|-------------------
Profile7	 | portable-net45+netcore45
Profile78	 | portable-net45+netcore45+wp8
Profile259 | portable-net45+netcore45+wpa81+wp8
Profile47	 | portable-net45+sl5+netcore45

**Comment by kurtschelfthout** [comment]
Sigh. Console output doesn't work on PCL (no System.Console. Makes sense.) But highly inconvenient...

**Comment by mstyura** [comment]
@kurtschelfthout believe it or not, I was not aware of this issue, but wanted to use `FsCheck` in our `WinRT` project at work. So couple of days (almost simultaneously as this issue has been opened, how does it possible?) I've decided to start working on migration to portable `Profile259`. So, I've done a bit of progress including migration to new reflection api where necessary, implementing quick and dirty workarounds for `System.Console` and `GetCultures` and fixing binding redirects and `CopyLocal` where necessary (according to [FSharp.Core notes](https://fsharp.github.io/2015/04/18/fsharp-core-notes.html)). I understand that my work is not necessary already, since you have almost done the same, but you may have a look is you want on what I've done here: https://github.com/mstyura/FsCheck/commits/portable-profile-259

**Comment by kurtschelfthout** [comment]
Wow, that's both good and bad timing :) Shame we did some of the work twice.

Could you try to rebase the last four commits you have there on top of latest and send a PR?

**Comment by mstyura** [comment]
@kurtschelfthout  
> Wow, that's both good and bad timing :) 

I should have opened an issue before getting myself to the place without Internet :)

> Shame we did some of the work twice

At least I've got familiar with some new things

> Could you try to rebase the last four commits you have there on top of latest and send a PR? 

Will be done

**Comment by mstyura** [comment]
@kurtschelfthout cherry picked last 4 commits and added 1 which fixes rebase conflicts. PR: #112

**Comment by kurtschelfthout** [comment]
Thanks! I will merge a bit later, had a horrible time just now trying to get the changes for reflection to work on mono...

**Comment by kurtschelfthout** [comment]
Closing this, 3/4 is not bad, maybe we don't need 47...
