### ISSUE TITLE
Example in Quick Start doesn't fail as expected

### ISSUE THREAD

**Issue by ronnieholm** [fscheck/FsCheck#114]
Following the Quick Start guide, this C# example doesn't fail:

    Prop.ForAll<double[]>(xs => xs.Reverse().Reverse().SequenceEqual(xs)).VerboseCheck();

I see "nan" in the output, but the test passes.

**Comment by kurtschelfthout** [comment]
That's interesting. turns out that ``Double.NaN.Equals(Double.NaN)`` is ``true``, while ``Double.NaN == Double.NaN`` is ``false``. 

``SequenceEquals``, unlike F#'s structural equality, uses IEquatable<Double> under the covers, which effectively boxes the double and uses ``Equals``. You can see in the referencesource that it checks for NaN explicitly, making two NaN equal! http://referencesource.microsoft.com/#mscorlib/system/double.cs,152

I think these semantics are completely insane, but there you go. 

If you pass in another comparer than the default into the ``SequenceEqual`` that uses ``==``, the test fails.
