### ISSUE TITLE
Gen.elements vs Gen.oneof

### ISSUE THREAD

**Issue by paulyoung** [fscheck/FsCheck#121]
Are these equivalent in terms of distribution and probability?

**Comment by kurtschelfthout** [comment]
Not sure those are comparable. `elements` chooses between the given elements uniformly. `oneof` chooses between the given generators uniformly - so it depends how those generators are defined.

For example, `Gen.elements [1;2;3]` is identical (but faster) to `Gen.oneof [Gen.constant 1; Gen.constant 2; Gen.constant 3]`, but not to `Gen.oneof [Gen.elements [1;2], Gen.constant 3]` because in the latter the value 3 has 50% chance of being generated, vs 33% in the former.
