### ISSUE TITLE
FsCheck.dll assembly should be signed

### ISSUE THREAD

**Issue by DmitryKakurin** [fscheck/FsCheck#152]
Here is why:
1. My Production code must be signed
2. My Production code uses [assembly: InternalsVisibleTo(MyUnitTest strong name)] to give unit test access to its internals.
3. The name MyUnitTest specified to InternalsVisibleTo MUST be a strong name, so MyUnitTest must be signed too
4. MyUnitTest cannot reference FsCheck.dll because FsCheck is not signed.

**Comment by mavnn** [comment]
Hi!
I'm not a maintainer here, but just a few quick notes:

* MUST is a bit of a rude way to express your desire that an unpaid open source maintainer should implement a feature for you that he does not require
* strongly named nuget packages can be very painful to consume, so I doubt the majority of users of FsCheck would desire it to be strong named
* the technical solution to your problem is fairly straight forward: FsCheck is open source and you can build and sign your desired version yourself but...
* I suspect that if your property tests require InternalsVisibleTo, you are almost certainly testing an implementation detail, not the observable behaviour of your code. This is not what property based testing is designed for, hence most people not requiring FsCheck to be strong named even if the rest of their code is

Hope that helps

**Comment by mausch** [comment]
Please see https://github.com/fscheck/FsCheck/issues/73

**Comment by Andrea** [comment]
+100 what @mavnn said

**Comment by kurtschelfthout** [comment]
Since this seems to keep coming up rather frequently, I'm going to try to put a general statement in the readme concerning strong naming, probably very similar to this: https://github.com/NancyFx/Nancy/wiki/Statement-on-strong-naming

I am not questioning your use case, as it is valid, but not very frequent and I don't feel like the cost of maintaining it is worth it for me.

**Comment by DmitryKakurin** [comment]
I didn't know I've stumbled on such a sensitive topic :-).
Have you considered publishing both signed and unsigned binaries as separate nugets?
Given the testing scenario the private key does not have to be a secret and can be checked in.

**Comment by jzabroski** [comment]
The private key must be a secret or your application will be vulnerable to man-in-the-middle attacks.  You shouldn't ship any ClickOnce applications with exposed secrets, as this gives attackers an attack vector into your application.  For example, it could then read all static fields from your trusted assembly.

**Comment by DmitryKakurin** [comment]
My production dll (signed by me) makes internals visible to unit test dll (signed by me) which references FsCheck.dll signed by "compromised" key. Obviously unit test dll never runs in production and is not even deployed with production code.
I don't see an attack vector here. Please be more specific.

**Comment by ploeh** [comment]
@DmitryKakurin, you [shouldn't test internals](http://blog.ploeh.dk/2015/09/22/unit-testing-internals). It's okay to have internal code, but it should be exercisable via a public API. If it isn't, that's a design issue, not a technical issue.

**Comment by jzabroski** [comment]
@DmitryKakurin The attack is a Confused Deputy attack, and would definitely require some "trampoline" function to execute, but it's doable.  All that needs to happen is have some code that loads your assembly and executes a static class constructor.  In the latest .NET, they have changed how some code is loaded, in particular, in mscorlib, it the behavior of GetInternalCustomAttributes was changed which would cause a property to be _touched_ if it had said attributes.  Boing - trampoline attack vector and confused deputy attack all-in-one.  Moreover, we can generalize this attack using static analysis to build "weaponry" on-the-fly by constructing "gadgets" that allow a property to be _touched_.

Bottom line: @kurtschelfthout  should never, ever give out his private key.

**Comment by DmitryKakurin** [comment]
@jzabroski Keep in mind that test dll is not present on the production system. The chain of trust is prod.dll -> test.dll -> fscheck.dll. The broken (compromised) link is test.dll -> fscheck.dll. By removing the test.dll from the picture the vulnerability disappears.

My proposal is a compromise.
If my choices were FsCheck signed by secret key vs. FsCheck signed by "compromised" key I'd obviously pick the first.
But if keeping the key secret is logistically prohibitively difficult, and my choices are no signed FsCheck vs. FsCheck signed by "compromised" key, I'd pick the second option because I know what I'm doing.

Also regarding:
> All that needs to happen is have some code that loads your assembly and executes a static class constructor.

You make it sound like it's easy :-). I'd say attacker has already won at that point.

**Comment by DmitryKakurin** [comment]
@ploeh Every time I hear a statements like this it reminds me of "[Only A Sith Deals In Absolutes](https://youtu.be/wgpytjlW5wU)" phrase :-). I hope you appreciate [the irony](http://scifi.stackexchange.com/questions/8067/if-only-the-sith-deal-in-absolutes-why-does-obi-wan-say-it-that-way).

**Comment by jzabroski** [comment]
The attacker hasn't won at that point.  It is easy.  Ever since a paper was published about 8 years ago about building "gadgets" out of smaller instructions, malware toolkits have been explosively more powerful.  You can use inductive reasoning software to automatically assemble gadgets to "mechanize" your exploit (weapon).  It's scary stuff...

At any rate, the bottom line is your proposal is a massive security hole.  I understand that _for you_ it may not be a problem, but _anybody else_ who thinks they are getting a _trusted assembly_ is screwed.  There is a community ethos among open source .NET developers that we don't lie about what we ship - if its trusted, it must actually be trusted.

**Comment by JeffLeBert** [comment]
Just so you know. I'm in the exact same situation. I have strongly named DLLs I want to test. It is a "legacy" application so I can't just rewrite everything. I use InternalsVisibleTo so I can get at the internal methods.

I was just preparing a quick presentation to the rest of my company to show how to use FsCheck. Since I couldn't reference FsCheck, I had to scrap the whole thing. We currently have several hundred developers across the company, all across the planet, that would have seen this. Now, I have to just say it is impossible to use. :-(

**Comment by kurtschelfthout** [comment]
The source code is available so if you want to produce a strong named FsCheck.dll, you can. If you want to sync with releases download the source zip from the releases page or check for the tags in the git history

Even assemblies you don't have the source for or you don't wish to compile yourself, you can sign using a tool like https://brutaldev.com/post/net-assembly-strong-name-signer

I have not changed my mind about strong naming FsCheck. It's a huge pain in the behind for 99% of users.

**Comment by ploeh** [comment]
@JeffLeBert It's been a while since I last had to work with a combination of strong-named .dlls and unnamed .dlls, so I could remember this incorrectly, but isn't it the other way around? You can reference a strong-named .dll from an unnamed .dll, but not the other way around?

**Comment by weshaggard** [comment]
@ploeh it correct the issue is with strong name assemblies referencing non-strong named assemblies. There is no pain for people to consume your library if you strong name sign it. I also don't buy the arguments about security as the .NET team has long stated that you should not rely on strong names for security (https://docs.microsoft.com/en-us/dotnet/framework/app-domains/assembly-security-considerations#strong-named-assemblies-and-signing-tools), but only for identity. Being a member of the .NET team for a long time I can tell you the .NET team actually checks in a full public/private key (see https://github.com/dotnet/buildtools/pull/407) used for strong name signing just to avoid all these issues with folks trying to consume your library from a strong named assembly on .NET Framework. 

As it stands I've recently had to tell some folks not to use this library because we don't wish to maintain a fork of the code to do the strong name signing. I'd highly recommend you strong name sign the library to avoid issues like this.

**Comment by kurtschelfthout** [comment]
@weshaggard ok, I'm intrigued. I didn't actually know that .NET Framework is the only thing that still forces exact assembly loading, which is the main problem I have with strong naming. 
https://docs.microsoft.com/en-gb/dotnet/standard/library-guidance/strong-naming

If anyone has any information about how assembly loading wrt strong naming works in .NET Core I'd like to hear about it; I could only find pretty sketchy info.

While I appreciate that binding redirects have been generated automatically, I find that that mechanism is still somewhat brittle in practice, because it requires changing app.config files on the fly, and they have an effect both at build and at runtime.

At the same time, this document seems to argue against strong naming "except in rare situations": https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md

Anyhow, I take it the suggestion is to:
- sign FsCheck with a private/public key that is checked in in this repo;
- to avoid assembly redirect issues, never to change the strong-named version number;
- release an FsCheck 3.0.0 to achieve this as the new version will be incompatible.

**Comment by JeffLeBert** [comment]
COOL!

@kurtschelfthout, the only thing I would change is "never to change the strong-named version number". You should be changing only across major releases. I'm OK with either.

In your last link, it says: "it is recommended that publicly published .NET libraries are strong-named." That's the "rule" I would use.

Thanks again for looking at this.

**Comment by weshaggard** [comment]
>If anyone has any information about how assembly loading wrt strong naming works in .NET Core I'd like to hear about it; I could only find pretty sketchy info.

There isn't any specific loading issues on .NET Core with respect to strong naming beyond it is part of the assembly identity. .NET Core will load and unify with the highest version already loaded that matches the identity (i.e. name and public key).

>At the same time, this document seems to argue against strong naming "except in rare situations": 

Yes it is needed in rare situations (depending on your scenarios) but as @JeffLeBert pointed out it does recommend strong name signing. 

>to avoid assembly redirect issues, never to change the strong-named version number;

I would not advise this, especially if there are API changes, as you will potentially get people into a broken state if there are multiple incompatible copies of your library in the dependency graph or worse someone puts your assembly in the GAC. I think you should still version your library following SemVer rules as close as possible. For better or worse the binding issues on .NET Framework have to be dealt with for any library, so playing tricks like not changing your version might burn you.

**Comment by kurtschelfthout** [comment]
Thanks very much for the pointers and explanation, all. I appreciate your time. 

I agree in principle to sign FsCheck 3.0. I think I’ll move the stuff currently on fscheck3 branch to some conclusion and delay some of the more invasive changes I had in mind to later (aka 4.0) so this could all happen soon. 

Remaining unclear point for me is that I don’t see what changing the version number will buy us on netframework.

First of all if the assembly identity remains the same it will only ever load one assembly, and there will be only one FsCheck assembly in the GAC. People will see missing method or the like if they use an assembly that is not compatible with their code. 

That sounds preferable to me over allowing different versions to be loaded and then to get weirder “can’t cast Arbitrary to Arbitrary” exceptions when they inevitably load different versions at the same time unknowingly.

It sounds like by unifying to the highest version this is effectively what all modern runtimes do too, and what is trying to be automated for netframework by writing app.config files. 

Note this is a particularly sensitive area for FsCheck, as it is often run via a test runner which dynamically loads test dlls. I’ve had lots of issues over the years trying to get NuGet to generate binding redirects in dll projects, and trying to get test runners to honour the test dlls app.config files.

**Comment by weshaggard** [comment]
>People will see missing method or the like if they use an assembly that is not compatible with their code.

That is the problem I was trying to help you avoid. If they run into that there may be no way for them to fix it at all because they may not be able to control which version of the library gets loaded (especially if an older version is in the GAC for some reason). 

On the other hand if multiple versions of the assembly get loaded then everything may work just fine as long as the code paths don't exchange types. Even if the do end up exchanging types they may have the opportunity to fix the issue by introducing a binding policy that allows the different versions to unify.

At the end of the day you are trading-off a different set of potential issues so feel free to make the trade-offs that best address your customers, but in my opinion I would bump the assembly version whenever you make API changes.

**Comment by akindle** [comment]
Hi! I ran into this issue while trying to use FsCheck in a strongly-named solution, and I found a simple workaround on NuGet: https://www.nuget.org/packages/StrongNamer/. Just thought I'd share in case this option is a viable workaround/solution for anyone else who runs into this issue 😃

**Comment by kurtschelfthout** [comment]
Fixed in https://github.com/fscheck/FsCheck/commit/c71f734f7c22f76f10403f747fd9c1231665f801

**Comment by roslynn** [comment]
It is a shame that it was not backported to version 2.* which still supports .net framework (version 3.* targets .net standard). Are you intending to graft this change?

**Comment by kurtschelfthout** [comment]
Afraid not, it is a breaking change after all.

From .NET Framework 4.6.1 onwards, you should be able to consume netstandard2.0 according to the docs.
