### ISSUE TITLE
Cover FsCheck.Xunit with some automated tests

### ISSUE THREAD

**Issue by moodmosaic** [fscheck/FsCheck#155]
To save some time from manually testing, _maybe_ we could cover FsCheck.Xunit with automated tests:

| Parametric properties |
| :-- |
| PropertyAttribute |
| PropertyAttribute derived types |
| PropertyAttribute with Arbitraries |

| Non-parametric properties |
| :-- |
| PropertyAttribute |
| PropertyAttribute derived types |

Most of the above scenarios were used to test #86 manually.

**Comment by kurtschelfthout** [comment]
In some sense this is already covered, in that FsCheck.Test uses FsCheck.Xunit to test FsCheck (yes, it makes my head hurt too).

What would be nice is some tests that specifically test the integration, i.e. passing test works, failing test works etc in all those cases. 

But I don't really know how to write those tests, i.e. how do I write a test (that passes) that runs an xunit test that fails and check the result? And can we check things like the visual studio integration works? Reliability - no false positives/negatives - is my main concern here.

**Comment by moodmosaic** [comment]
>And can we check things like the visual studio integration works?

No, I think we can't test this automatically, because we would be relying on particular test-runners.

>In some sense this is already covered, in that FsCheck.Test uses FsCheck.Xunit to test FsCheck

Agreed on this one.

>What would be nice is some tests that specifically test the integration

I'd be quite interested in verifying `QuietOnSuccess` via automated test(s).

If such tests were in place, we'd have probably [avoided going back and forth](https://github.com/fscheck/FsCheck/pull/145) on that one. Then, we can probably extrapolate for other properties as well. But to be honest I don't really know how to write those tests either.

**Comment by kurtschelfthout** [comment]
I know of one way to write them - by running the console runner in a separate process and check the outputs - but that just seems like asking for trouble.

**Comment by ploeh** [comment]
Perhaps... FsCheck could be written as a library of side-effect-free queries, reporting status as return values instead of writing to the console :stuck_out_tongue_winking_eye: 

If so, it'd be possible to test the return values of those queries.

At the boundary, FsCheck could still write those return values to the console.

**Comment by ploeh** [comment]
Bantering aside, there's quite a bit of untested logic in PropertyAttribute.fs, and it might be a good idea to refactor it so that the implementation is as pure and testable as possible, leaving only the glue to xUnit.net untested.

I'll be happy to look into that whenever I have a bit of time, but I'll need to first understand how the xUnit.net 2 extensibility API works...

**Comment by kurtschelfthout** [comment]
Yes...I'm actually in favour of rewriting the runner a bit so we can get the return values out. It's probably not that far off, but in the ignorance of my youth I decided long ago to use a callback-like interface to get the results. We are still paying the price.

**Comment by ploeh** [comment]
You're thinking about `XunitRunner`?

A rewrite of that might be appropriate as well, but that's not what I had in mind. While it's mutable, it looks like it's simple enough that nothing much can go wrong there... I could be wrong, though.

What I had in mind was `PropertyTestCase`. It has to be there because it's the main integration with xUnit.net, but the implementation could be extracted to pure functions.

**Comment by kurtschelfthout** [comment]
No, sorry, I meant the vanilla FsCheck runner (Runner.fs) and the interface the library exposes to that and the extensions.

**Comment by ploeh** [comment]
I see. Changing that would be a breaking change, so I'll leave that to you to decide on :smile:

**Comment by kurtschelfthout** [comment]
Yeah, exactly.

**Comment by ploeh** [comment]
Since *FsCheck.Test* already uses *FsCheck.Xunit*, we can add tests *of* *FsCheck.Xunit* to *FsCheck.Test*, but where would you want to put those?

There's already a file called *Property.fs* there, but it seems concerned with something completely different.

Would it make sense to add a file called *PropertyAttributeTests.fs*, which would cover the features implemented in *PropertyAttribute.fs*?

**Comment by ploeh** [comment]
I've begun the work of simply figuring out how to create an instance of `PropertyTestCase` and invoke its `RunAsync` method. This type is shaped by the xUnit.net 2 API, because it needs to derive from the appropriate base class.

It turns out that the xUnit.net 2 API is quite... object-oriented, with lots of inheritance and interfaces deriving from other interfaces and so on.

Just to create an instance of `PropertyTestCase` and invoke its `RunAsync` method, I'll need to supply an `IMessageSink`, an `ITestMethod`, an `IMessageBus`, plus configure some of those interfaces to return other interface implementations from some of their methods.

I started to create some Test Doubles of the necessary interfaces using object expressions, and this is certainly doable, but will result in quite a lot of test infrastructure code in order to support all the required interfaces.

An alternative is to pull in a dynamic mock library. We could, for example, try out [Foq](https://github.com/fsprojects/Foq) - I don't have much experience with it, but it's written in F# by someone I trust :smile: 

My preference is to try adding Foq as a package to the test project only, but I'm also OK with going the *object expression route*; I only wanted to ask before I started adding a lot of code.

**Comment by moodmosaic** [comment]
If those interfaces are [Role Interfaces](http://martinfowler.com/bliki/RoleInterface.html), I'd just go with object expressions. It's a wild guess, but I think that object expressions are more optimized, in terms of performance, than [custom MSIL instructions](https://github.com/fsprojects/Foq/blob/6a1091114e2337d111dd11b7423da906be25e772/Foq/Foq.fs#L63).

On the other hand, if those interfaces are [Header Interfaces](http://martinfowler.com/bliki/HeaderInterface.html), I'd definitely choose Foq, or any other similar library, as it'll require less code and thus less maintenance :smiley:

**Comment by kurtschelfthout** [comment]
@ploeh I defer to you.

**Comment by ploeh** [comment]
FWIW, I had two or three false starts on this, both with or without a mocking library. It turns out that while xUnit.net's extensibility API is interface-based, the interfaces are so complex, and xUnit.net itself has so strict expectations about how these objects interact, that I gave up.

I'd recommend closing this issue as _not realistic in practice_.

**Comment by kurtschelfthout** [comment]
Fair, and thanks very much for looking.
