### ISSUE TITLE
FsCheck.Xunit doesn't support C# async tests

### ISSUE THREAD

**Issue by Porges** [fscheck/FsCheck#167]
With a test like:

```
[Property]
public async Task TestWhatever(int i)
{
    Assert.True(await DoSomething(i));
}
```

The Xunit runner fails with:

```
 System.Exception:
 No instances of class FsCheck.Testable+Testable`1[a] for type System.Threading.Tasks.Task
```

**Comment by kurtschelfthout** [comment]
This could be tricky, as we need to pass have some static data (in particular, the overridden arbitrary instances) around. Currently this is done using a thread static, because xunit2 by default runs different tests in parallel. But if we have async tests together with that we'd need to pass them accross async boundaries too.

Perhaps something like http://stackoverflow.com/questions/6896652/threadstatic-for-tpl-task helps.

**Comment by Porges** [comment]
Hmm, so a custom synchronization context might be required. I'll try to investigate this weekend and see if there's a sane solution...

**Comment by ploeh** [comment]
@kurtschelfthout Would it be possible to move FsCheck in a direction where reliance on thread-static data isn't required?

**Comment by kurtschelfthout** [comment]
@ploeh Yes, but not without giving up a few features, in particular the ability to override Arbitrary instances and configure them via e.g. PropertyAttribute.

For vanilla FsCheck this is not a huge deal I think - though you lose the ability to e.g. override the string generator and still use the reflective generator to generate a large record type that contains strings, using your custom generator. But that could be solved by allowing you to pass in those overrides to the reflective generator. (Not sure I am making sense to you here)

The bigger change is that essentially the arguments to methods with a PropertyAttribuite could only come from the immutable default Arbitrary instances, and you couldn't customize them. So, essentially you'd have to use Prop.ForAll much more frequently.

This can work - it's what Erlang quickcheck does - but obviously a breaking change.

**Comment by ploeh** [comment]
I'm not sure I understand this... If we consider the [current implementation of the PropertyAttribute](https://github.com/fscheck/FsCheck/blob/master/src/FsCheck.Xunit/PropertyAttribute.fs#L112), there's no thread-static state involved in that library. It collects Arbitraries (`Type list`) and binds those immutable values to a `Config` value, and then calls into FsCheck proper...

**Comment by kurtschelfthout** [comment]
Here is what gets set by Config: https://github.com/fscheck/FsCheck/blob/master/src/FsCheck/Arbitrary.fs#L131

It is likely possible to not rely on side-effects to register Arb instances and pass the them all the way into the Gen type...

**Comment by Porges** [comment]
I had a go at this, the changes needed weren't very big. It works on the small examples I have added and all the current tests still pass.

**Comment by kurtschelfthout** [comment]
CallContext I did not know about, kind of interesting, but I think the right way to fix is to use AsyncLocal, but that would require us to switch to .NET 4.6.

Even righter would be if I could figure out a way to pass the registered instances around, but don't think that's possible without actually changing the API (aka FsCheck 3).

So it seems like AsyncLocal is our best hope short term. I wonder how people would feel about requiring .NET 4.6. Perhaps we could multi-target (i.e. if you want to write async tests, use .NET 4.6)

**Comment by ploeh** [comment]
> if you want to write async tests, use .NET 4.6

I never really understood the desire to write async tests... What's the motivation for this?

**Comment by kurtschelfthout** [comment]
@ploeh The desire is not so much for async tests, but easily being able to test async code in the SUT afaik. How would you test async code?

**Comment by ploeh** [comment]
> How would you test async code?

In F#: `Async.RunSynchronously`

In C#: `.Result` or `.Wait()` for non-generic `Task`.

**Comment by kurtschelfthout** [comment]
In C# that most likely deadlocks (at least in e.g. mstest), because when the async Task finishes it tries to get back on the main thread, but that is waiting for the async one to finish...

**Comment by ploeh** [comment]
I don't know what's going to happen in MsTest, but I've never had a problem with this approach in xUnit.net.

To be clear, I never define my test functions or methods as async; they always return `unit`/`void` (or `Property` in the case of FsCheck).

**Comment by kurtschelfthout** [comment]
It depends in what sort of context you're running these things. If you're running them in a single-threaded context, they will deadlock. xUnit.Net, at least 2.0 onwards runs test in parallel by default so this sort of thing will work.

Point is, it's already complicated enough without your test framework having to add a bunch of ifs and buts of its own, so I'd like this to work in all cases, rather than some, or at least make it blatantly obvious when it's going to work and when not.

**Comment by ploeh** [comment]
This is probably derailing the discussion a bit, but I don't understand this. Isn't the point of async to *avoid* blocking threads?

If I have a `Task<int>` called `i`, and I call `i.Result`, why would a test deadlock?

Granted, calling `Result` blocks the *calling* thread, but lots of things do that. From the caller's perspective, isn't this similar to invoking `Thread.Sleep`?

**Comment by kurtschelfthout** [comment]
`Result` blocks the calling thread, and in a single-threaded context (e.g. when you have a message pump, like in a UI), when the async call returns, it will try to get the result back on the calling thread. But that thread is blocked on `Result` until the async call returns, which can't return because it can't get its result on the calling thread because it's blocked on `Result`, etc

**Comment by ploeh** [comment]
This does makes some sense to me in the context of integration testing, but I don't understand how this can ever apply to unit tests. Perhaps it's just me being dense... :flushed:

**Comment by Porges** [comment]
Yes, it fits integration testing, but in addition, if your classes under
test are very async it doesn't make sense to write your tests in a
synchronous manner.

There's also no reason that FsCheck *shouldn't* work with async tests ☺

**Comment by kurtschelfthout** [comment]
My opinion on all that is that any test is better than no test, and so there's not reason to make testing harder than it has to be. 

Not a big fan of "this is not a real unit test", it reeks of no true Scotsman, and waving a dictionary around never helped anyone (outside the occasional game of scrabble).  *shrug* ;)

**Comment by ploeh** [comment]
It was never my intention to turn this into a discussion about what a 'real' unit test is; I genuinely didn't understand what the point was - perhaps because I sometimes take too narrow a view on things.

I can't say that I fully understand, but I think I understand when it would be useful to support async tests.

Thank you for making me a little less stupid :smile:

**Comment by Porges** [comment]
Another reason is that Xunit supports `Task`-returning methods for `[Fact]` or `[Theory]` tests, and it's unfortunate to not have it for `[Property]` tests as well :smiley:

**Comment by bradphelan** [comment]
Any progress on this. Just tried the below as an experiment

    [Property()]
    public async Task IntersectingLineWithPlaneShouldReturnIntersectionPoint(Vector3 position, Vector3 forward, Vector3 up)
    {
    
        await Task.Delay(TimeSpan.FromMilliseconds(10));
    }
	
and got


FsCheck.Xunit.PropertyFailedException

Falsifiable, after 1 test (0 shrinks) (StdGen (1120699755,296208179)):
Original:
(<0.5, 0.333333333333333, 0.25>, <0.4, -0.454545454545455, 0.166666666666667>,
 <-0.666666666666667, 0.666666666666667, 0.25>)

  Exception doesn't have a stacktrace

    System.Exception
    No instances of class FsCheck.Testable+Testable`1[a] for type System.Threading.Tasks.Task
       at FsCheck.TypeClass.GetInstance@156-1.Invoke(String message) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\TypeClass.fs:line 156
       at FsCheck.TypeClass.GetInstance@145.Invoke(Type instance) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\TypeClass.fs:line 156
       at FsCheck.Common.f@1[a,b](IDictionary`2 memo, FSharpFunc`2 f, a n, Unit _arg1) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\Common.fs:line 25
       at FsCheck.Common.memoizeWith[a,b](IDictionary`2 memo, FSharpFunc`2 f, a n) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\Common.fs:line 20
       at FsCheck.Testable.evaluate[a,b](FSharpFunc`2 body, a a) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\Testable.fs:line 161
       
Any progress on this?

**Comment by kurtschelfthout** [comment]
No, probably not happening until 3.0.

**Comment by kurtschelfthout** [comment]
This is now in pre-release in NuGet in 3.0-alpha1: https://www.nuget.org/packages/FsCheck/3.0.0-alpha1

Please try it out and open new issues in case of problems.

**Comment by dustinmoris** [comment]
> I don't know what's going to happen in MsTest, but I've never had a problem with this approach in xUnit.net.
> 
> To be clear, I never define my test functions or methods as async; they always return `unit`/`void` (or `Property` in the case of FsCheck).

I've been directed to this issue after refactoring some tests in Giraffe to avoid using `.Result` and `Async.RunSynchronously`, because it was starving threads with xunit. I thought I'll link it here as it's not something someone would necessarily expect:

https://github.com/aspnet/Hosting/issues/1537
https://github.com/giraffe-fsharp/Giraffe/pull/317

**Comment by Choc13** [comment]
I've just come across this issue and subsequently tried the latest alpha, 3.0.0-alpha5. It seems to work fine for me (providing I convert the task to an async with `Async.AwaitTask`, which isn't a problem). I was just wondering what your intentions were around releasing a stable v3 as it seems like it's been in alpha for several years. 

I only ask because I'd like to know whether to stick with the alpha for the time being or not.

**Comment by kurtschelfthout** [comment]
I think it’s fine to use it - I’ve been considering getting 3.0 out pretty much as is, and moving all the long term stuff to a subsequent version.

**Comment by dgrozenok** [comment]
I'm using xUnit with FsCheck alpha, 3.0.0-alpha5 for integration testing with async functions in C#. The Property attribute on the async test method works great. However, sometimes it's beneficial to be able to use Prop.ForAll<> to have more granular control over the execution of the tests. In addition I'm considering to start using Fixie where the Property attribute would not be available. Is it possible to have the async function in the parameter for the Prop.ForAll<>?

Something like this:

```
[Fact]
public void Test_async_function()
{
    Prop.ForAllAsync<int>(async i => await Task.Delay(1000));
}
```

If I just do it for the current implementation of the Prop.ForAll<>

```
[Fact]
public void Test_async_function()
{
    Prop.ForAll<int>(async i => await Task.Delay(1000));
}
```
the body function is not awaited and all the iterations are executed in parallel, which is bad for the integration test as they all use the same database. You can see that this example finishes in a couple of seconds, but should be running for more than a hundred.

**Comment by kurtschelfthout** [comment]
I think I see what is going on -

Your second example calls this overload:

```
    ForAll(body:Func<'Value,Threading.Tasks.Task<bool>>)
```

While there is no corresponding overload that returns a `Task` so it chooses this a non-async overload, which then doesn't run your async function.

The fix in principle would be to add an overload like

```
 ForAll(body:Func<'Value,Threading.Tasks.Task>)
```
but that confuses the compiler because `Task<T>` is a subtype of `Task`. 

Have no great ideas at the moment, but meanwhile I'd advise you use something like your second example. The boolean return type indicates whether your test passes or fails. It will still also fail if you throw an exception, so if you wish to not use that you can always `return true` and use assertion libraries as normal.

**Comment by dgrozenok** [comment]
Thank you! This is helpful. I also didn't realize I needed to call QuickCheckThrowOnFailure() to see the results of the failed tests. So for now I just made a helper static class like this. And BTW, at least the C# compiler wasn't confused about the Task vs Task<bool>:
```
    public static class PropAsync
    {
        public static void ForAll<TValue>(Func<TValue, Task> f)
        {
            Prop.ForAll<TValue>(async v =>
            {
                await f(v);
                return true;
            }).QuickCheckThrowOnFailure();
        }
        
        public static void ForAll<TValue>(Func<TValue, Task<bool>> f)
        {
            Prop.ForAll<TValue>(async v =>
            {
                return await f(v);
            }).QuickCheckThrowOnFailure();
        }
    }
```
And I use it like this:
```

        [Fact]
        public void Test_async_function()
        {
            PropAsync.ForAll<int>(async i =>
            {
                await Task.Delay(100);
                i.ShouldBePositive();
            });
        }
```

**Comment by kurtschelfthout** [comment]
Good to know about the overloading, perhaps it has been made better. I tested this a long time ago :)
