### ISSUE TITLE
Config and Configuration

### ISSUE THREAD

**Issue by MarcoMaar** [fscheck/FsCheck#203]
I have a question regarding the configurations that are used to Check a property

For example at ```Check.One<Testable>(Config config, Testable property)``` a configuration of the type ```Config``` is used where all properties of are readonly. 

But at ```CheckExtensions.CheckCheck(this Property property, Configuration config)``` a configuration of the type ```Configuration``` is used where you can change the values, however the ```CheckExtensions.VerboseCheck``` extension does have an overload that takes a ```Configuration```instance

I am curious why ```Config``` is read only, why there are two types of configurations and why ```CheckExtensions.VerboseCheck``` does not take a configuration .

For me it would be convenient if there is only one configuration , where it is possible to change single properties of it.

**Comment by mausch** [comment]
The mutable `Configuration` and associated extension methods are meant for C# . Once you pass your `Configuration` instance to e.g. `CheckExtensions.Check` it is converted to the immutable `Config` type.
If you're writing your tests in F#, use the immutable `Config` type. F#'s copy-and-update syntax makes it trivial to change single properties (giving you a new instance of course).

**Comment by MarcoMaar** [comment]
Okay, that makes sense. Thank you.
I am still wondering why the Verbose functions don't have an overload with a configuration.

**Comment by kurtschelfthout** [comment]
Because verbosity configures, via `Config` or via `Configuration` what gets printed when certain events happen (e.g. value tested, value shrunk, etc). And so Quick and Verbose are just two particular configurations. So basically a method Check.Verbose or Check.Quick that takes a configuration is ambiguous (because it would somehow need to "merge" two configurations, the verbose one and the given one).

I guess we could add some static methods to `Configuration` that return the quick, verbose and default `Configuration` instances; we have a similar thing on `Config`.

**Comment by MarcoMaar** [comment]
I just updated my previous answer the moment you wrote.
If it is okay to add those static methods that would be nice. Will you take care of it or should I do that?

**Comment by kurtschelfthout** [comment]
Sure, go for it.

**Comment by kurtschelfthout** [comment]
Released in 2.2.5.
