### ISSUE TITLE
Arb.From(Gen.Fresh(lamba)) appears to re-use previously generated values

### ISSUE THREAD

**Issue by Aaronontheweb** [fscheck/FsCheck#217]
Ran into a weird bug with a property test today, given the following generator:

```csharp
public class HeliosGenerators
    {
        public static Arbitrary<CircularBuffer<T>> CreateCircularBuffer<T>()
        {
            Func<CircularBuffer<T>> generator = () =>
            {
                var randomSize = ThreadLocalRandom.Current.Next(1, 10);
                var buffer = new CircularBuffer<T>(randomSize);
                return buffer;
            };

            return Arb.From(Gen.Fresh(generator));
        }

        public static Arbitrary<CircularBuffer<int>> CreateCircularBufferInt()
        {
            return CreateCircularBuffer<int>();
        }
    }
```

And the following property test:

```csharp
[Property(QuietOnSuccess = true)]
        public Property CircularBuffer_size_is_always_accurate(CircularBuffer<int> buffer, int[] itemsToAdd)
        {
            var currentSize = buffer.Size;
            if (currentSize > 0) return false.Label($"Began with invalid buffer size {currentSize}. Should be 0. Head: {buffer.Head}, Tail: {buffer.Tail}");
            for (var i = 0; i < itemsToAdd.Length; i++)
            {
                var full = currentSize == buffer.Capacity;
                var expectedSize = full ? currentSize : currentSize + 1;
                buffer.Enqueue(itemsToAdd[i]);
                var nextSize = buffer.Size;
                if (nextSize != expectedSize)
                    return false.When(buffer.Capacity > 0).Label($"Failed with {buffer} on operation {i}. Expected size to be {expectedSize}, was {nextSize}");
                currentSize = nextSize;
            }
            return true.ToProperty();
        }
```

I noticed in the debugger that I was receiving instances of `buffer` that had already been pre-populated with values. I was able to filter out those failing cases with a precondition, but according to the comments for Gen.Fresh I should be getting a fresh instance every time. Is there something I should be doing differently?

**Comment by kurtschelfthout** [comment]
Yes, this is because of shrinking. The generated instance is always fresh, but during shrinking it tries to make the example smaller by re-executing the test. `CircularBuffer` does not define a shrinker, but `int[]` does, and so basically the test fails, and then the shrinking process starts on the `int[]` argument. This is the main reason for having things like `StateMachine`, to "unroll" the mutable value in an immutable sequence of operations (which can then be shrunk). `Gen.Fresh` really has relatively limited usability.

Anyway, you can work around this for now by asking FsCheck not to shrink anything. There is no global option for that at the moment by you can wrap each type in `DontShrink`:

```
public static Property CircularBuffer_size_is_always_accurate(CircularBuffer<int> buffer, DontShrink<int[]> itemsToAddS)
        {
            var itemsToAdd = itemsToAddS.Item;
```

You can also clone the CircularBuffer at the beginning of your test, and do all the operations on the clone, leaving the original untouched. That should work as well.

Also, it's best not to use source of randomness other than methods on the `Gen` type, like the ThreadLocalRandom. That ensures that if FsCheck gives you a seed value, you can replay the test exactly as many times as you want. In this case, I would write:

```
        public static Arbitrary<CircularBuffer<T>> CreateCircularBuffer<T>()
        {
            var generator = Gen.Choose(1, 10).Select(i => new CircularBuffer<T>(i));
            return Arb.From(generator);
        }
```

**Comment by Aaronontheweb** [comment]
> You can also clone the CircularBuffer at the beginning of your test, and do all the operations on the clone, leaving the original untouched. That should work as well.

Yeah, that's what I ended up doing - called `Clear()` on the buffer to reset it since this particular property requires an empty buffer every time.

**Comment by Aaronontheweb** [comment]
> Also, it's best not to use source of randomness other than methods on the Gen type, like the ThreadLocalRandom. That ensures that if FsCheck gives you a seed value, you can replay the test exactly as many times as you want. In this case, I would write

Could you please include that snippet as an example? I was banging my head against the wall trying to figure out how to get concrete values out of Gen for that exact purpose.

**Comment by kurtschelfthout** [comment]
> Yeah, that's what I ended up doing - called `Clear()` on the buffer to reset it since this particular property requires an empty buffer every time.

That'll work in this particular case, thiugh base rule is if you want to use a generator for a mutable type don't touch the generated instance. So cloning is a more general solution. I didn't mention it before but usually if I do this kind of thing I don't even bother with creating generators for the mutable types; I just generate the necessary ingredients to create an instance and create a new instance in the test itself. This also works generally, and shrinking works almost for free!

```
public Property CircularBuffer_size_is_always_accurate(int[] itemsToAdd) {
    Prop.ForAll(Arb.From(Gen.Choose(1, 10)), capacity => {
        var buffer = new CircularBuffer<int>(capacity);
        //rest of test goes here, as before.
    }
}
```

Or if you don't mind if the capacity is > 10:

```
public Property CircularBuffer_size_is_always_accurate(PositiveInt capacity, int[] itemsToAdd) {
    var buffer = new CircularBuffer<int>(capacity.Get);
}
```

I think it's worth documenting all that, perhaps in the FAQ or a separate section - testing mutable objects or something.

> Could you please include that snippet as an example? I was banging my head against the wall trying to figure out how to get concrete values out of Gen for that exact purpose.

Ok, where do you think it should go? `Gen.Choose` is discussed under Generators here: https://fscheck.github.io/FsCheck/TestData.html the snippet there uses LINQ syntax but I think is otherwise equivalent.

Anyway, also have a look at `Arb.Default` to get access to all built-in generators and shrinkers (which should also figure more prominently somewhere...)

**Comment by kurtschelfthout** [comment]
Closing this as both the sample and some more info about this approach for testing mutable objects is up in the tips and tricks section now.
