### ISSUE TITLE
How do I see the test cases that were generated when not using the FSI

### ISSUE THREAD

**Issue by jamessdixon** [fscheck/FsCheck#261]
I created 2 projects in a VS2015 solution.  Project 1 is a example working code project and Project 2 is an example unit test project - much like you would do in C#.  In the test project, I created a test method where I ran Check.Verbose

```
    [<TestMethod>] 
    member this.GetStockPrice_Better() =
        let picker = new StockPicker()
        let property = picker.GetStockPrice
        Check.Verbose property
        ()
```

and the working code looks like this:

```
type StockPicker() = 
    member this.GetStockPrice(basePrice) = 
        basePrice + 1.0
```

I want to see what values were generated by FSCheck but there is nothing in the Output after I run the test in Test Explorer.  Is there a way to see it?

Thanks

**Comment by ploeh** [comment]
IIRC, `Check.Verbose` (and `Check.Quick`) writes test run results to the standard output stream. Can you see the information in the Visual Studio _Output_ window?

If you can't, there's probably an explanation for that, although I don't know if the following holds for _MSTest_. In _xUnit.net_, at least, the test runner(s) now suppress the standard output stream, because writing to it isn't thread safe. Instead, in _xUnit.net_, one has to use a special API to write to an output stream. It could be that the same is the case for the _MSTest_ runner.

In any case, `Check.Verbose` and `Check.Quick` _only_ reports test success or failure to the console. These functions _don't_ fail if a property fails.

You probably want to use `Check.QuickThrowOnFailure` instead. This function will, as the name implies, throw an exception if the property fails. IIRC, the exception message will contain information about the values used, and how you can reproduce the test case.

**Comment by jamessdixon** [comment]
Nothing in the output window.  Drat.  My guess is that you are right.
I did change the function call to Check.QuickThrowOnFailure

Thanks

**Comment by ploeh** [comment]
In any case, have you considered using _xUnit.net_ instead? FsCheck comes with an official Glue Library called [FsCheck.Xunit](https://www.nuget.org/packages/FsCheck.Xunit). With it, you can write properties as easy as this:

```fsharp
[<Property(QuietOnSuccess = true)>]
let ``Game state always contains original cards`` deck (PositiveInt round) =
    let actual = War.unfold "Player One" "Player Two" deck |> Seq.item round
    (List.sort deck) =! (allCards actual |> List.sort)
```
