### ISSUE TITLE
Generating values of provided types

### ISSUE THREAD

**Issue by ploeh** [fscheck/FsCheck#306]
In F#, I can use the JSON type provider to define a type from a JSON document:

``` fsharp
open FSharp.Data

type Foo = JsonProvider<"""
{
    "foo": 42,
    "bar": "baz"
}
""">
```

Obviously, this is only a simple example. In reality, the JSON document could be much more complex.

It'd be nice to be able to ask FsCheck to generate values of such types:

``` fsharp
open FsCheck

let ``An intance of Foo can't be automatically generated`` () =
    Arb.from<Foo.Root>
    |> Prop.forAll <| ignore
    |> Check.QuickThrowOnFailure
```

Unfortunately, this doesn't work:

```
System.Exception :
The type FSharp.Data.Runtime.BaseTypes.IJsonDocument is not handled automatically
by FsCheck. Consider using another type or writing and registering a generator for it.
```

Clearly, it's possible to overcome this problem by explicitly defining a generator:

``` fsharp
let ``An instance can be created`` () =
    gen {
        let! foo = Arb.generate<int>
        let! bar = Arb.generate<string>
        return Foo.Root (foo, bar) }
    |> Arb.fromGen
    |> Prop.forAll <| ignore
    |> Check.QuickThrowOnFailure
```

This works for this toy example, but if the JSON document is big and complicated, it'd require considerable maintenance.

It'd be nice if this 'just worked'. The same with the XML provider, for that matter.

Can anything be done about this?

I'll be happy to submit a pull request if this is something that seems possible and desirable, but I thought I'd ask here before starting investigation.

**Comment by kurtschelfthout** [comment]
Interesting problem! Here is a brain dump...

I believe the majority, if not almost all, type providers are erasing type providers. This basically means that the types the provider generates at compile time, do not exist at runtime. I mention this because the whole machinery in FsCheck to associate `Arbitrary` instances with types, depends on those types being available at runtime. So, it you want to, say, create a generator for the JSON type provider, really what you want to do is figure out what the underlying type is that the provider erases to, and write a generator for that. (All this and the below also applies to shrinking; I will omit to mention shrinking explicitly though)

However, the story does not end there. Because clearly, the type parameter(s) you give to the JSON type provider limit the sort of documents that the generator should generate; or in other words, you can't "just" write a generator for `IJsonDocument` - you'd also somehow have to feed the schema that the actual type provider uses to the generator somehow, so it can generate only instances that satisfy that schema.

In addition, the _compile time_ types also have to work out - in other words, you now have a generator that generates values at runtime with type `IJsonDocument` that conform to the schema - but at compile time you need values of type `Foo.Root`! How can you do that? Maybe one possibility is to write a generator type provider that takes the same input as the JSON type provider but statically creates types like `Gen<Foo>`. This provider would be a sort of wrapper around the JSON type provider - passing through the types it generates and adding something else to it. Not sure if that is possible. Perhaps it is over-complicated anyway, and we just need some casts in the right places...this is where I would start experimenting with a simple example to check what's what.

Finally, generally my approach has been to add out-of-the box `Arbitrary` instances for anything that doesn't force FsCheck to take on additional dependencies. So perhaps for XML we could add an `Arbitrary` instance since that is in .NET proper, but for JSON I would be reluctant. I would be very happy to start curating a set of projects with `Arbitrary` instances for other libraries under the FsCheck organization though. If the projects themselves are willing, we could also try to PR them ("here is a set of FsCheck generators for user-visible types in your project"). Anyway, that's a bit off topic for this thread.

**Comment by moodmosaic** [comment]
>I would be very happy to start curating a set of projects with Arbitrary instances for other libraries under the FsCheck organization though.

Not a bad idea at all; they do similar in Haskell ([servant-quickcheck](https://hackage.haskell.org/package/servant-quickcheck), [tasty-quickcheck](https://hackage.haskell.org/package/tasty-quickcheck), [quickcheck-regex](https://hackage.haskell.org/package/quickcheck-regex), and more).

In fact, if it's not simple, tricks for creating gen/shrink pairs out of erased types could live on a separate project as well.

**Comment by giacomociti** [comment]
@moodmosaic in fact your [Fare](https://github.com/moodmosaic/Fare) may be enhanced to provide `Arbitrary` instances of regex based strings. I'm already using it in [AntaniXml](https://github.com/giacomociti/AntaniXml), although at the moment the generated regex strings have their own random seed.

**Comment by moodmosaic** [comment]
@giacomociti yes, [that's possible](https://github.com/moodmosaic/FsCheck.Regex/blob/master/README.md).

**Comment by giacomociti** [comment]
Nice, thanks. 
I'm continuing the discussion [there](https://github.com/moodmosaic/FsCheck.Regex/issues/1) because here it would be completely off topic

**Comment by ploeh** [comment]
Most likely I didn't think this through before I wrote, but I thought that the JSON and XML providers were _not_ erasing type providers. If they are (and I believe you), then I understand that everything becomes much harder.

I'd be happy to close this issue again, then.

**Comment by kurtschelfthout** [comment]
Pretty much all type providers are erasing - major exception I know of is the Linq to SQL type provider. There may be others, but they're a lot harder to create.

**Comment by kurtschelfthout** [comment]
I think this is a pretty long shot, so closing as part of spring cleaning. Feel free to re-open if you disagree.
