### ISSUE TITLE
Has fscheck got much slower since 3.0.2

### ISSUE THREAD

**Issue by KevinRansom** [fscheck/FsCheck#326]
Hi,

we have a set of tests using fscheck in the F# repo.  I have tried updating to a more recent build 3.5.0 and 3.6.2.

our coreclr version of tests seem to take much ... much longer.  In fact I haven't had the patience to allow them to run to completion yet.  Although they didn't seem to have hung when I broke into them with the debugger.

Have they got a lot slower ... or is there some magic go faster knob I should implement.

Thanks

Kevin

**Comment by kurtschelfthout** [comment]
Sorry I'm confused - I'm assuming you went from **2**.0.2 to **2**.6.2?

If anything I would expect things to run faster because there were a bunch of optimizations added.

But if it's only coreclr tests that are taking longer, there could be something more insidious going on. For example, in [2.0.3](https://github.com/fscheck/FsCheck/blob/master/FsCheck%20Release%20Notes.md#203---10-july-2015) we added PCL support, which I think gets picked up by CoreCLR in some cases. Something could go wrong there.

Oh, and something just dawned on me. in [2.5.0](https://github.com/fscheck/FsCheck/blob/master/FsCheck%20Release%20Notes.md#250---7-june-2016) we made a change so that the test size (which determines how "big" generated data structures are, say tree like types get more levels, lists are longer etc) increases. This can cause some dramatic runtime changes, esp. if tests rely on `==>` for example.

Can I take a look at something - a few pointers would be appreciated?
