### ISSUE TITLE
FsCheck is not defined (after clean NuGet install)

### ISSUE THREAD

**Issue by Biarity** [fscheck/FsCheck#328]
Using Visual studio: create a new F# library, install `FsCheck` using NuGet, then try `open`ing it. You'll get an error `The namespace or module FsCheck is not defined`. Same error when using `FsCheck.Xunit` and `FsCheck.NUnit`. 

Tried updating `Fsharp.Core` and using various versions, doesn't fix anything. Also tried using a script file instead with `#r`, still doesn't work.

**Comment by ploeh** [comment]
Clearly such a scenario is supposed to work, which it also normally does when I do it. Please share some more details: Which version of Visual Studio? Which target platform for the F# library? How do you add the NuGet package? UI? Command line? Where are you writing the `open` directive?

**Comment by Qudware** [comment]
Sure, I'm using Visual Studio 2017 RC. I am targeting .NET Framework 4.5 (I really have no choice anyway, .NET Core is really bad with F#). I got the package through the UI (NuGet Package Manager in VS). The `open` is present in a freshly created F# Library project, no modifications at all. Also the VS installation is unmodified in any way (just installed).

If you are unable to reproduce this, I'm ready to give more detailed instruction. This maybe a VS 2017 issue because I've noticed the same thing in a different library (except in that one, restarting VS fixes the issue).

**Comment by ploeh** [comment]
I don't have Visual Studio 2017, and since I have no problem with FsCheck in Visual Studio 2015, I'd be inclined to theorise that the problem is related to that. 

Perhaps someone else can attempt to reproduce the problem in order to narrow it down.

**Comment by kurtschelfthout** [comment]
Is there a reference to FsCheck added to the project file if you open References, any yellow exclamation marks? Is the package (and dll) present in the packages folder?

Maybe easier, can you send the contents of the fsproj file you installed the package in.

**Comment by kurtschelfthout** [comment]
Closing b/c inactivity. Feel free to re-open if you need any more help.
