### ISSUE TITLE
Where do you place the call to Arb.register?

### ISSUE THREAD

**Issue by cmeeren** [fscheck/FsCheck#390]
I want to register generators for some new types, e.g. `EvenInt` and `OddInt`. Currently I can only get it working by using the `Properties` or `Property` attribute on every module/test where it's relevant; it seems that no matter where I put the call to `Arb.register`, it's never called. I'm using the ReSharper test runner, in case that's relevant (no text editor support, but it discovers and runs tests when you compile).

**Comment by ploeh** [comment]
FWIW, I found [this old post of mine](http://blog.ploeh.dk/2014/03/11/arbitrary-version-instances-with-fscheck) where I used `Arb.register` before I learned of better ways of using FsCheck.

Looking at [the source code](https://github.com/GreanTech/Champagne/blob/86e893c923786e62e3a6091dc1c8618f531eacaa/Src/Champagne.FSharp.UnitTests/Tests.fs), it looks like I was calling the function in the test class constructor...

**Comment by ploeh** [comment]
TBC, I'm not claiming that it's the correct way to do it...

**Comment by cmeeren** [comment]
Yes, that should work. I don't have any test classes, though. I'm using XUnit and making file/module hierarchies similar to my production code, with an additional test module level at the bottom for each function that contains all the tests/properties for that function. As you say, though, I'm not sure that's the correct way - I'm just getting started with FP, let alone unit testing FP code.

**Comment by kurtschelfthout** [comment]
There's no single way to answer that question, except that clearly `Arb.register` needs to be called before you want to generate any data that use those Arbitrary instances. Various test frameworks and various ways of structuring tests have different answers. Note in FsCheck.Xunit you can also use `PropertiesAttribute` attribute to configure tests - including `Arbitrary` instances - on the module or class level.

**Comment by cmeeren** [comment]
Yes, `Properties` is what I'm currently using.

Speaking of which, is there any good reason it only works for tests directly below the module it's defined on, and not lower in the hierarchy? I would like to specify `PropertiesAttribute` on the top-level module in my test files, but since I have at least two levels of modules above the tests, it doesn't work.

**Comment by kurtschelfthout** [comment]
> Speaking of which, is there any good reason it only works for tests directly below the module it's defined on, and not lower in the hierarchy?

No. Just not implemented.

**Comment by cmeeren** [comment]
I see. I created #394 to get it on the issue list. :)

**Comment by ploeh** [comment]
FTR, [I still think `Arb.register` should die...](https://github.com/fscheck/FsCheck/issues/334#issuecomment-268362575)

**Comment by kurtschelfthout** [comment]
@ploeh 

>FTR, I still think Arb.register should die...

To try and put ideas in your head, I think one significant step in that direction would be to allow the default instances in `Arb.Default` to be parametrized. For example,  `FsList() : Arbirtrary<list<'a>>` which derives the arbitrary instance for `'a` by looking it up in the type to instance dictionary that's manipulated by `Arb.register`. To promote the explicit style, there should be a method `FsList(elementArb:Arbitrary<'a>)` which allows users to specify directly what that should be.

And of course, the same for all the other generic instances...

**Comment by ploeh** [comment]
It's possible that I'm missing something, but why would that be required, or even desirable?

Regardless of how it's done, removing `Arb.register` would be a breaking change, but apart from that, the only action required would be to remove it.

I can delete `Arb.register` and `Arb.registerByType` from the FsCheck code base, and the only code that doesn't compile is a few tests. Even among these, if I comment out the calls to `Arb.register`, the entire FsCheck build script runs to completion with only a single failing test (which I can then comment out to make the entire build succeed).

Thus, removing `Arb.register` is trivial to do. It's still a breaking change, but why do you think that something else needs to be done.

I haven't used `Arb.register` since 2014. I've been using FsCheck professionally on and off since then, without ever using `Arb.register`, so I can attest that there's already plenty of alternatives available in the FsCheck API.

**Comment by kurtschelfthout** [comment]
@ploeh It's desired or even required to make the one use case for `Arb.register` possible that isn't easily done in the `Prop.forAll` explicit style:

 I use `Arb.register` to avoid having to write a generator/shrinker by hand for types that are otherwise entirely out-of-the box generated by FsCheck (say a larger record type that contains nested lists of primitive types and union types etc), but where I want to tweak some of the default generators. For example, I don't want null or empty strings to be generated. With `Arb.register` this is easy - I just override the desired generators for the desired types in the register call, then have FsCheck generate the rest with the overridden generator.

Without `Arb.register` I'd have to go through the tedious process of re-writing the entire generator and srhinker from the ground up.

**Comment by ploeh** [comment]
If you do something like that, aren't you changing how `string` values are generated for all other tests that'll happen to run on the same thread?

**Comment by kurtschelfthout** [comment]
@Ploeh Yes. The usual issues with global state.

**Comment by ploeh** [comment]
> The usual issues with global state.

Just to make explicit what those are:

- Each test must run in a serialised fashion. Tests can't run in parallel.
- Each test must guarantee that it resets the global state to its initial value once the test has completed.
- That 'reset guarantee' must take into account that a test may throw an exception during execution.

Particularly the issues related to robust failure tolerance in the face of global mutable state come with substantial baggage.

I'm not convinced that this, in practice, is 'easy'. Ultimately, if you have a scenario where tests become difficult to write, this could also be an indication that the SUT ought to be simplified, or decomposed.

**Comment by kurtschelfthout** [comment]
I'm not sure I get your point. I totally agree the `Arb.register` mechanism is less than perfect, but that does not say anything about the validity of the use case I've described above.

**Comment by ploeh** [comment]
When you write a test, you write code that uses the SUT. One could make the argument that if the test code is hard to write, it's feedback that the SUT is hard to use. It's an overarching theme of [GOOS](http://bit.ly/growingoos). You don't have to agree with that viewpoint, but that was part of what I meant.

**Comment by kurtschelfthout** [comment]
I think you have to distinguish between code that is hard to write because the SUT makes it so, or because the (testing) tools you use make it so. 

Why would you make someone re-write code to generate and shrink a type like:

```fsharp
type Person = {
LastName: string
Age: int option
}
```
Where what is being tested assumes the name is not null and age is non-negative? Perhaps it's a component that can assume the data is validated. Perhaps we are only testing positive cases because we don't want to waste time checking for exceptions repeatedly. 

I would like to be able to write `Arb.from<Person>(MyArb.NonNullString, MyArb.PositiveInt)` or something along those lines - otherwise I'm being forced to re-invent a record type _and_ an option type generator:

```fsharp
let personGen = gen {
  let! lastName = MyArb.NonNullString.Generator
  let! age = MyArb.PositiveInt.Generator
  let ageOption = //etc
  return { LastName = lastName; Age = ageOption }
}
let personShrink = ... //etc
```

If you're advocating a style where each of those fields should have their own type (i.e. `Name` instead of `string` and `Age` instead of `int`) with their restrictions built-in, then I would say that there are circumstances where that is useful, but I'd hate to have that style uniformly imposed on me by a testing (or other) tool.

**Comment by ploeh** [comment]
I don't want to be quarrelsome, so I'll only state that I disagree, and leave it at that... After all, the only problem I have with `Arb.register` is that it blocks parallel execution... Apart from that, I just ignore that it's there...

**Comment by kurtschelfthout** [comment]
OK, well, time to close then :)
