### ISSUE TITLE
Can these Arbitraries (gen+shrinker) be simplified?

### ISSUE THREAD

**Issue by cmeeren** [fscheck/FsCheck#391]
I'm trying to implement Arbitraries (gens+shrinkers) for some constrained types, such as `CloseDateInterval` and `NonEmptyNonWhitespaceString`. I find the documentation a bit confusing and lacking in examples. I have something that seems to work, but I have no idea if this is the best way to do it.

I'd simply like anyone to take a quick look and tell me if I'm on the right track or if, as I suspect, I've missed some more elegant way of doing it.

Here's the code for `CloseDateInterval`:

```f#
/// A tuple with two dates no more than 500 days apart
type CloseDateInterval = CloseDateInterval of DateTime * DateTime with
    // Do I need to implement this? What happens if not?
    static member op_Explicit(CloseDateInterval (x1, x2)) = (x1, x2)

let private gen2CloseDateTimes maxDaysApart =
    gen {
        let! d1 = Arb.generate<DateTime>
        let! d2 = Arb.generate<DateTime>
        let d2 = DateTime(d1.Year, d1.Month, d1.Day, d2.Hour, d2.Minute, d2.Second)
        let! daysApart = Gen.choose (-maxDaysApart, maxDaysApart)
        return (d1, d2.AddDays(float daysApart))
    }

type ArbitraryAdditions =
    static member CloseDateInterval() = 
        let shrinker (d1, d2) =
            let shrink = Arb.Default.DateTime().Shrinker
            (shrink d1, shrink d2) ||> Seq.zip
        Arb.fromGenShrink ((gen2CloseDateTimes 500), shrinker)
        |> Arb.convert CloseDateInterval (fun (CloseDateInterval (d1, d2)) -> (d1, d2))
```

And here's the code for `NonEmptyNonWhitespaceString`:

```f#
type NonEmptyNonWhitespaceString = NonEmptyNonWhitespaceString of string with
    // Do I need to implement this? What happens if not?
    static member op_Explicit(NonEmptyNonWhitespaceString s) = s

type ArbitraryAdditions =
    static member NonEmptyNonWhitespaceString() =
        let filter s = 
            not (isNull s) && s <> "" && s |> Seq.forall (not << System.Char.IsWhiteSpace)
        let arb =
            Arb.from<string>
            |> Arb.filter filter
            |> Arb.convert NonEmptyNonWhitespaceString string
        let shrinker (NonEmptyNonWhitespaceString s) = 
            let shrink = Arb.Default.String().Shrinker
            shrink s |> Seq.filter filter |> Seq.map NonEmptyNonWhitespaceString
        Arb.fromGenShrink (arb.Generator, shrinker)
```

Whenever I need these types generated, I simply add

```f#
[<Properties(Arbitrary = [|typeof<TestHelpers.ArbitraryAdditions>|])>]
```

to the module containing the tests, or using the `Property` attribute if I only need it on a single test. (I know you can also register them, but I'm having trouble with that, see #390.)

**Comment by ploeh** [comment]
You don't need the explicit conversions. Instead, you can just return new values from your generators, like this:

```fsharp
let private gen2CloseDateTimes maxDaysApart =
    gen {
        let! d1 = Arb.generate<DateTime>
        let! d2 = Arb.generate<DateTime>
        let d2 = DateTime(d1.Year, d1.Month, d1.Day, d2.Hour, d2.Minute, d2.Second)
        let! daysApart = Gen.choose (-maxDaysApart, maxDaysApart)
        return CloseDateInterval (d1, d2.AddDays(float daysApart))
    }
```

Normally, I'd have written the above generator by generating `d1`, and then selecting between two tick values, calculated like

```fsharp
let  maxTicks = maxDaysApart * TimeSpan.TicksPerDay
```

Unfortunately, you can't use `maxTicks` with `Gen.choose` because it's a 64-bit integer, and `Gen.choose` only works with 32-bit integers...

FsCheck already has a built-in `NonEmptyString` type. Could you use that?

**Comment by cmeeren** [comment]
> You don't need the explicit conversions. Instead, you can just return new values from your generators, like this:

Nice, but I still need to do all the other ceremony I already do in creating a shrinker, right? So I don't really save any significant code with your approach? Or did I misunderstand?

> FsCheck already has a built-in `NonEmptyString` type. Could you use that?

Unfortunately not.  I need one that produces no whitespace characters. I have another one too, `NonNullString`, which can be empty but not null (I don't want to deal with null unless I have to).

**Comment by ploeh** [comment]
You do need to define shrinkers independently of generators. FWIW, there's a newer project called [Hedgehog](https://github.com/hedgehogqa/fsharp-hedgehog) that has automatic shrinking, but I've yet to spend the time to actually understand how it works.

On a slightly different note, I've been using FsCheck for years, and rarely bothered with creating custom shrinkers. It all depends on context, obviously, but I usually find that when a test fail, I don't need a shrinker to tell me why. Tests tend to not fail unexpectedly - when they fail, it's almost always because I changed some code in the SUT, and it's normally quite clear to me what the problem is - even without shrunk values... YMMV.

**Comment by cmeeren** [comment]
Good point. It's easy to get carried away with new shiny tools like FsCheck (not to mention F#!) and forget all about pragmatism for a while.

Is it necessary to implement `op_Explicit` on the new types? What usage does it serve, and what happens if you remove it?

**Comment by cmeeren** [comment]
And, if there's no need for shrinkers, is there perchance a more succinct way to use generators without having to wrap them in Arbitraries and specify them in `Property` attributes (or register them)? I know it's possible to use them in an inline function, but [TIE fighters](http://blog.ploeh.dk/2016/05/17/tie-fighter-fscheck-properties/) notwithstanding, I'm not too fond of that and would rather all input to the test be specified in the arguments.

**Comment by ploeh** [comment]
> On another note, is it necessary to implement op_Explicit on the new types? What usage does it serve, and what happens if you remove it?

No, it's not necessary. It's an explicit type conversion. Why did you add it?

>  is there perchance a more succinct way to use generators without having to wrap them in Arbitraries

No, but you can create an Arbitrary (without a shrinker) from a `Gen` using `Arb.fromGen`.

You may be able to use `Arb.register` to avoid explicit use of generators. Yes, I'm aware of #390, but haven't had the time to look at it yet... (Personally, though, I prefer the explicit combination of generators to both `Arb.register` and the use of the `Arbitrary` property of the `[<Property>]` property (sic), because that's the type-safe way to do it...)

**Comment by cmeeren** [comment]
> No, it's not necessary. It's an explicit type conversion. Why did you add it?

It's [in an example in the docs](https://fscheck.github.io/FsCheck/TipsAndTricks.html#Use-pattern-matching-instead-of-forAll-to-use-custom-generators), and it doesn't really explain that well what's going on. Based on my experience from https://github.com/fscheck/FsCheck/issues/392#issuecomment-329848081 I get why it was done that way; it allowed the use of `int` to convert instead of `fun (EvenInt i) -> i`.


> Personally, though, I prefer … because that's the type-safe way to do it

I'm likely missing something obvious, but on what level is it more type safe? Isn't creating single-case DUs and taking them as parameters as type-safe as it gets, since F# doesn't have constrained types (by which I mean, there is no way to encode "string without whitespace" or "even numbers" in the type system)?

**Comment by kurtschelfthout** [comment]
> On another note, is it necessary to implement op_Explicit on the new types?

It is there to make the function `int:'a -> int`  work in the example.

**Comment by ploeh** [comment]
> It is there to make the function `int:'a -> int` work in the example.

Perhaps we should simplify that example so that it doesn't confuse newcomers. It can be rewritten like this:

```fsharp
type EvenInt = EvenInt of int

type ArbitraryModifiers =
    static member EvenInt () = 
        Arb.from<int> 
        |> Arb.filter (fun i -> i % 2 = 0) 
        |> Arb.convert EvenInt (fun (EvenInt i) -> i)
```

**Comment by ploeh** [comment]
> I'm likely missing something obvious, but on what level is it more type safe? Isn't creating single-case DUs and taking them as parameters as type-safe as it gets[?]

That's not really type-safe, in the sense that you can take a single-case DU as an input argument, but if you forget to register the Arbitrary (or if you make an implementation error), then you'll get a run-time exception because FsCheck doesn't know how to correctly generate values of your custom DU.

The latter problem happens often. You can find plenty of questions on the internet (Stack Overflow, or the present issue list) where, for example, people have attempted to write their Arbitrary types like this:

```fsharp
type ArbitraryAdditions =
    static member CloseDateInterval = 
        let shrinker (d1, d2) =
            let shrink = Arb.Default.DateTime().Shrinker
            (shrink d1, shrink d2) ||> Seq.zip
        Arb.fromGenShrink ((gen2CloseDateTimes 500), shrinker)
        |> Arb.convert CloseDateInterval (fun (CloseDateInterval (d1, d2)) -> (d1, d2))
```

What's wrong with this type? It compiles, but it's going to fail at run-time. The problem is that `CloseDateInterval` is a value instead of a function.

That mechanism is, IMO, too fragile.

---

In the type-safe alternative, you don't need to define custom DUs at all. In order to generate the above range of `DateTime` values, you can simply do this:

```fsharp
let private gen2CloseDateTimes maxDaysApart =
    gen {
        let! d1 = Arb.generate<DateTime>
        let! d2 = Arb.generate<DateTime>
        let d2 = DateTime(d1.Year, d1.Month, d1.Day, d2.Hour, d2.Minute, d2.Second)
        let! daysApart = Gen.choose (-maxDaysApart, maxDaysApart)
        return d1, d2.AddDays(float daysApart) }

[<Property>]
let ``Example: no custom types required`` () =
    gen2CloseDateTimes 500
    |> Arb.fromGen
    |> Prop.forAll <| fun (d1, d2) ->
        // d1 and d2 are both DateTime values.
        // Test body using d1 and d2 go here...
        ()
```

You can also inline the `gen` expression if you're really doing a one-off expression:

```fsharp
[<Property>]
let ``Example: inline an entire gen expression`` () =
    gen {
        let! d1 = Arb.generate<DateTime>
        let! d2 = Arb.generate<DateTime>
        let d2 = DateTime(d1.Year, d1.Month, d1.Day, d2.Hour, d2.Minute, d2.Second)
        let! daysApart = Gen.choose (-500, 500)
        return d1, d2.AddDays(float daysApart) }
    |> Arb.fromGen
    |> Prop.forAll <| fun (d1, d2) ->
        // d1 and d2 are both DateTime values.
        // Test body using d1 and d2 go here...
        ()
```

I use both of these alternatives, depending on what I find most readable. In this particular example, I may prefer the top alternative (an explicitly named `gen2CloseDateTimes` function) because it better communicates the intent of the test.

Both alternatives, however, are type-safe, because if you remove the expressions, or change their types, you'll get compilation errors.

I also find that this style works much better in practice, because often you need to exercise mutually exclusive test cases. For instance, you may have one test cases where you verify that the SUT behaves correctly when two dates are within 500 days of each other, but then you also need to verify the opposite test case where two dates are explicitly more than 500 days apart.

With the registration mechanism, you'll need to define a custom type for each case (say, `CloseDateInterval` and `FarDateInterval`), and register them both - even thogh you're never going to use them both together. I consider that far more ceremony than simply inlining the specific `gen` expression I need for a particular test case.

**Comment by cmeeren** [comment]
I understand now; you make a good point, and I'll try out your way and see if I like it better.

The only thing that's puzzling me is this:

> if you forget to register the Arbitrary (or if you make an implementation error), then you'll get a run-time exception because FsCheck doesn't know how to correctly generate values of your custom DU.

By "run-time exception", do you mean "failing tests"? As long as you're taking DUs/records as parameters, won't FsCheck simply create them according to the usual rules for their constituent parts (e.g. `DateTime` in the case of `CloseDateInterval`), likely failing the test if invalid values are passed? Was that perhaps what you meant?

**Comment by ploeh** [comment]
That's exactly the sort of problem you could run into. For a DU that takes a well-known value like `DateTime`, IIRC FsCheck is just going to fill it with two unconstrained values.

This can be particularly difficult to spot if the difference between the custom Arbitrary and the default generator is subtle. You could, indeed, risk that the difference only manifests once in tens of thousands of values, so you could be seeing [false negatives](http://xunitpatterns.com/false%20negative.html) most of the time, with only an occasional test failure. If one doesn't pay attention, then, one could interpret such a test failure as a fluke.

In other cases, if you're asking for a type of value that FsCheck doesn't know how to produce by default, a missing registration would result in a run-time exception.

**Comment by cmeeren** [comment]
I'm trying to inline some generators/arbs now, but I'm having trouble with a property that needs a list of even ints and a list of odd ints. It's nice and clean if I define an `EvenInt` separately like this:

```f#
type EvenInt = EvenInt of int

type ArbitraryAdditions =
    static member EvenInt() =
        Arb.from<int>
        |> Arb.filter (fun i -> i % 2 = 0)
        |> Arb.convert EvenInt (fun (EvenInt i) -> i)
```

and similarly for ``OddInt``, and then define the property as

```f#
let myProperty (xs:EvenInt list) (ys:OddInt list) = ...
```

When inlining this, however, I struggle to do it in a clean way that does not force me to implement the list-specific stuff (which FsCheck can do automatically using the method above). How could `my property` be defined using inline definition or gens/arbs?

**Comment by ploeh** [comment]
For that particular example, you can just let FsCheck generate any `ints : int list`, and then partition them:

```fsharp
let evens, odds = ints |> List.partition (fun i -> (i % 2) = 0)
```

**Comment by kurtschelfthout** [comment]
Seems like we are done here, feel free to re-open if not.

**Comment by kurtschelfthout** [comment]
Heh, I still had this tab open and while closing it there is something that I missed:

```fsharp
type ArbitraryAdditions =
    static member NonEmptyNonWhitespaceString() =
        let filter s = 
            not (isNull s) && s <> "" && s |> Seq.forall (not << System.Char.IsWhiteSpace)
        let arb =
            Arb.from<string>
            |> Arb.filter filter
            |> Arb.convert NonEmptyNonWhitespaceString string
        let shrinker (NonEmptyNonWhitespaceString s) = 
            let shrink = Arb.Default.String().Shrinker
            shrink s |> Seq.filter filter |> Seq.map NonEmptyNonWhitespaceString
        Arb.fromGenShrink (arb.Generator, shrinker)
```

That shrinker is superfluous. When you use the methods on `Arb`, you are effectively defining generator and shrinker at the same time. So this is equivalent to:

```fsharp
type ArbitraryAdditions =
    static member NonEmptyNonWhitespaceString() =
        let filter s = 
            not (isNull s) && s <> "" && s |> Seq.forall (not << System.Char.IsWhiteSpace)
        Arb.from<string>
        |> Arb.filter filter
        |> Arb.convert NonEmptyNonWhitespaceString (fun (NonEmptyNonWhiteSpaceString s) -> s)
```
And the shrinker is defined automatically in the same way you defined it.

**Comment by cmeeren** [comment]
Thanks! That is, in fact, exactly what I ended up with. Forgot to post it here.

**Comment by cmeeren** [comment]
One more:

I have an `OrderLine` with (among other things) 6 optional float fields, defined as

```f#
OrderLine = {FactoryPriceNet: float option; CostPriceNet: float option; ...}
```

These float parameters are never `NaN` or `Inf`, which do, of course, crop up when FsCheck creates `OrderLine` instances in tests. This makes it hard to compare two instances, since `NaN = NaN` is always false, and I could also have some business logic that relies on these never being `NaN` or `Inf` (a fair assumption in many cases).

I've tried creating an Arbitrary for `OrderLine` that uses `NormalFloat` to populate the fields, but using `Arb.Convert` I could only come up with this monstrosity (remember, there are six float values on the record, and some more):

```f#
static member OrderLine() =
    Arb.from<...*NormalFloat option*NormalFloat option*NormalFloat option
                *NormalFloat option*NormalFloat option*NormalFloat option>
    |> Arb.convert
        (fun (..., v1, v2, v3, v4, v5, v6) -> 
            {...
            OrderLine.FactoryPriceNet=Option.map float v1;
            OrderLine.CostPriceNet=Option.map float v2;
            ...})
        (fun ol -> (...,
                    Option.map NormalFloat ol.FactoryPriceNet,
                    Option.map NormalFloat ol.CostPriceNet, ...))
```

Is there a more concise way to do this?

**Comment by kurtschelfthout** [comment]
> Is there a more concise way to do this?

Ha, That's exactly the case @ploeh and I were discussing in #390. 

What you could do, since it looks like you're using `Arb.register` or `Properties` which uses that under the hood, is in the same class as you're defining the `OrderLine()` method, and which presumably gets passed as an argument to `Properties` or `Arb.register` somehwere, define:

```fsharp
static member Float() = Arb.Default.NormalFloat() |> Arb.convert float NormalFloat
```
And you don't need to define a `static member OrderLine()` if you have no other modifications to the default generator/shrinker for it.

This essentially overrides the default float generator everywhere for the test, including in FsCheck's reflection based `Arbitrary` construction.

As @ploeh explained in #390 this can be confusing and has certain annoying side-effects, esp. with `Task` based test parallelism it currently doesn't work. I would want to change this in v3 so you can do something like:
`Arb.fromWithOverride<OrderLine>(Arb.Default.NormalFloat())` which has none of those downsides, and then remove `Arb.register` and friends.

**Comment by cmeeren** [comment]
Yes, I've been following #390 and figured it was probably exactly that but I didn't fully understand everything. With my current understanding of the issue, I'll just say that I'm generally fully in favor of everything that makes tests significantly simpler to write (which is why I started using FsCheck in the first place) without sacrificing too much robustness.

Thanks for the tip, I'll check it out.

**Comment by kurtschelfthout** [comment]
Sounds like we're now really done.
