### ISSUE TITLE
Implement Arb.choose?

### ISSUE THREAD

**Issue by cmeeren** [fscheck/FsCheck#400]
I might soon write some types that can only be constructed using functions (often static members) of the `tryCreate` kind that return `MyType option`. When creating an Arb mapper for this, it would be great if I could just use e.g.

```f#
Arb.from<string*int>()
|> Arb.choose MyType.tryCreate
```

As far as I can see, currently I'd have to use (written from memory, might not compile)

```f#
Arb.from<string*int>()
// (string * int) <-> MyType option
|> Arb.convert MyType.tryCreate (fun x -> (x.Value.MyString, x.Value.MyInt)) 
// filter
|> Arb.filter Option.isSome
// MyType option <-> MyType
|> Arb.convert (fun x -> x.Value) Some
```

which, apart from involving three operations for something that could be done in one, will also scale poorly for an increasing number of arguments due to the second conversion function to the first Arb.convert call.

**Comment by kurtschelfthout** [comment]
I've not had need for such a function, so am hesitant to add it to the API for a single use case. It's easy enough to add a helper function in your project. I think it would look like:

```fsharp
    let choose (choiceFun:'T -> 'S option) (convertBack:'S -> 'T) (arb:Arbitrary<'T>) : Arbitrary<'S> =
        let g = arb.Generator |> Gen.map choiceFun |> Gen.where Option.isSome |> Gen.map Option.get
        let s a = a |> convertBack |> arb.Shrinker |> Seq.map choiceFun |> Seq.where Option.isSome |> Seq.map Option.get
        Arb.fromGenShrink (g,s)

    let myTypeArb = 
        Arb.from<int*string>
        |> Arb.choose MyType.tryCreate (fun myType -> myType.TheInt, myType.TheString)
```

As you can tell because of the shrinker, some mapping back to the original generated values is necessary. If you omit the shrinking part it's trivially possible to have your desired signature.

Another but more involved possibility is to somehow remember separately what the original values were that generated a `MyType` instance (in this case `int*string`), and on shrinking somehow access those values and make them smaller according to their shrinker, then reconstruct `MyType` with them (and filter again for `isSome`). I don't really know how to do that though in the current implementation of FsCheck - without maybe rewriting a lot of code - but it's possible provided `tryCreate` is a pure function.

**Comment by cmeeren** [comment]
I see; of course a reverse mapping is needed for shrinker support. Your helper function looks like it could do the trick.
