### ISSUE TITLE
Update FsCheck.Xunit to reference xunit 2.3

### ISSUE THREAD

**Issue by mjmckp** [fscheck/FsCheck#402]
Is there any reason FsCheck.Xunit is still referencing xunit 2.2?

**Comment by ploeh** [comment]
Yes, [Postel's law](https://en.wikipedia.org/wiki/Robustness_principle). If _FsCheck.Xunit_ doesn't need _xUnit.net_ 2.3 in order to do what it needs to do, there's no reason to force that version on all users.

There could be other users of  _FsCheck.Xunit_ who, for various reasons, can't upgrade to _xUnit.net_ 2.3. Updating _FsCheck.Xunit_ to that specific version of _xUnit.net_ would break those users' code.

You can still use _FsCheck.Xunit_ with _xUnit.net_ 2.3. Just update _xUnit.net_ to 2.3 after you've installed _FsCheck.Xunit_. You may have to add a binding redirect, but assuming that _xUnit.net_ 2.3 contains no breaking changes, that ought to be all you need to do.

I admit that I haven't tried this particular combination, though, but I've done this countless times with previous versions of both involved packages, and it's always worked out like that.

**Comment by mjmckp** [comment]
XUnit 2.3 is required for .NET Core 2.0.  However, FsCheck.XUnit doesn't work with XUnit 2.3, at least with the msbuild runner.   Within a single test assembly, plain old XUnit `Fact`s are run, while FsCheck properties are not, and no warning or error is generated.  I've tried this with binding redirects for the xunit assemblies and .NET framework 4.7 (before even getting to .NET Core 2.0).

**Comment by kurtschelfthout** [comment]
Can you provide repro steps? FsCheck itself is using FsCheck.Xunit for its test library, and I am running locally on .NET Core 2.0. It all seems to work. Though I am using `dotnet xunit`.

**Comment by ploeh** [comment]
I've tried the combination, and it seems to be working fine with both the xUnit.net console runner, [TestDriven.net](http://www.testdriven.net), and the Visual Studio test runner.

# Test

```fsharp
module Tests

open FsCheck.Xunit

[<Property>]
let repro (x : int) = x = x
```

# Packages

```
PM> Get-Package

Id                                  Versions
--                                  --------
FsCheck                             {2.10.3}
FsCheck.Xunit                       {2.10.3}
FSharp.Core                         {4.1.18}
Microsoft.NETCore.Platforms         {1.1.0} 
Microsoft.Win32.Primitives          {4.3.0} 
NETStandard.Library                 {1.6.1} 
System.AppContext                   {4.3.0} 
System.Collections                  {4.3.0} 
System.Collections.Concurrent       {4.3.0} 
System.Console                      {4.3.0} 
System.Diagnostics.Debug            {4.3.0} 
System.Diagnostics.DiagnosticSource {4.3.0} 
System.Diagnostics.Tools            {4.3.0} 
System.Diagnostics.Tracing          {4.3.0} 
System.Globalization                {4.3.0} 
System.Globalization.Calendars      {4.3.0} 
System.IO                           {4.3.0} 
System.IO.Compression               {4.3.0} 
System.IO.Compression.ZipFile       {4.3.0} 
System.IO.FileSystem                {4.3.0} 
System.IO.FileSystem.Primitives     {4.3.0} 
System.Linq                         {4.3.0} 
System.Linq.Expressions             {4.3.0} 
System.Net.Http                     {4.3.0} 
System.Net.Primitives               {4.3.0} 
System.Net.Sockets                  {4.3.0} 
System.ObjectModel                  {4.3.0} 
System.Reflection                   {4.3.0} 
System.Reflection.Extensions        {4.3.0} 
System.Reflection.Primitives        {4.3.0} 
System.Resources.ResourceManager    {4.3.0} 
System.Runtime                      {4.3.0} 
System.Runtime.Extensions           {4.3.0} 
System.Runtime.Handles              {4.3.0} 
System.Runtime.InteropServices      {4.3.0} 
System.Runtime.InteropServices.R... {4.3.0} 
System.Runtime.Numerics             {4.3.0} 
System.Security.Cryptography.Alg... {4.3.0} 
System.Security.Cryptography.Enc... {4.3.0} 
System.Security.Cryptography.Pri... {4.3.0} 
System.Security.Cryptography.X50... {4.3.0} 
System.Text.Encoding                {4.3.0} 
System.Text.Encoding.Extensions     {4.3.0} 
System.Text.RegularExpressions      {4.3.0} 
System.Threading                    {4.3.0} 
System.Threading.Tasks              {4.3.0} 
System.Threading.Timer              {4.3.0} 
System.ValueTuple                   {4.3.1} 
System.Xml.ReaderWriter             {4.3.0} 
System.Xml.XDocument                {4.3.0} 
xunit.abstractions                  {2.0.1} 
xunit.core                          {2.3.0} 
xunit.extensibility.core            {2.3.0} 
xunit.extensibility.execution       {2.3.0} 
xunit.runner.console                {2.3.0} 
```

# Console runner output

```
$ packages/xunit.runner.console.2.3.0/tools/net452/xunit.console FsCheckXunit23Test/bin/Debug/FsCheckXunit23Test.dll
xUnit.net Console Runner (64-bit Desktop .NET 4.0.30319.42000)
  Discovering: FsCheckXunit23Test
  Discovered:  FsCheckXunit23Test
  Starting:    FsCheckXunit23Test
  Finished:    FsCheckXunit23Test
=== TEST EXECUTION SUMMARY ===
   FsCheckXunit23Test  Total: 1, Errors: 0, Failed: 0, Skipped: 0, Time: 0,555s
```

# Output from TestDriven.Net

```
------ Test started: Assembly: FsCheckXunit23Test.dll ------

Output from Tests.repro:
  Ok, passed 100 tests.

1 passed, 0 failed, 0 skipped, took 1,28 seconds (xUnit.net 2.3.0 build 3820).
```

# Output from Visual Studio test runner

In order to make the Visual Studio test runner run xUnit.net tests, one must also add the _xunit.runner.visualstudio_ NuGet package. When I did that, I could also run my property using the built-in _Test Explorer:_

![image](https://user-images.githubusercontent.com/242165/31371990-072beecc-ad94-11e7-93ba-671d6ba8153b.png)


---

These tests are all on .NET 4.6.1. I don't know about .NET Core... No assembly redirects seem to have been necessary. I've tested this in Visual Studio 2017 Community Edition.

**Comment by mjmckp** [comment]
I've got it working now, thanks Mark - it turns out `xunit.core.targets` adds `<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>` true, and the test project I was using was missing the import of this file.  Sorry for wasting your time!
