### ISSUE TITLE
Add QuickCheckThrowOnFailure possible with custom config object?

### ISSUE THREAD

**Issue by nathvi** [fscheck/FsCheck#466]
I have the following code:

    [TestMethod]
    public void TestMethod1()
    {
        var config = new Configuration();
        config.MaxNbOfTest = 20000;
        Prop.ForAll(new Func<int, bool>(MultiplyBy2_ResultIsTwiceNumber))
         .Check(config);
    }

I'm wondering if it is somehow possible to pass in the custom config object to the **Check** method, but still have the **QuickCheckThrowOnFailure** functionality?

**Comment by kurtschelfthout** [comment]
Look at the static factory methods on `Configuration`. E.g. start with `Configuration.QuickThrowOnFailure` (instead of `new Configuration()`) and then set properties on that config object. Then pass the result into `Check`.

In other words, `QuickCheckThrowOnFailure` is really just a shorthand for `Check(Configuration.QuickThrowOnFailure)`.

**Comment by nathvi** [comment]
Thanks.
