### ISSUE TITLE
FsCheck.Xunit - Default lists producing an infinite series of identical values

### ISSUE THREAD

**Issue by tknightnd** [fscheck/FsCheck#500]
Hi,

With the following deliberately failing test:

```
[Property(Verbose = true, Replay = "(1,1)")]
public Property List_Fails(List<string> values, string value)
{
  Func<bool> predicate = () =>
  {
    values.Add(value);
    return values.First() == value;
  };

  return predicate.When(values != null && value != null && values.Count < 10);
}
```

```values``` is generated with the same values. After the first singleton lists are generated, ```values``` settles to ```[null, null]``` and ```["",null] ``` infinitely and the test never terminates.

The packages are FsCheck.Xunit 2.14.0, xunit 2.4.1 over .net core 2.2. Downgrading to FsCheck.Xunit 2.13.0 shows the same behaviour. If you need any more information, please ask. 

Thanks for the package!

**Comment by kurtschelfthout** [comment]
What's happening here is that because this test is changing the mutable `values` list inside the test FsCheck gets confused while it is trying to shrink, that is, while it is trying to find a smaller value than the randomly generated one that still fails the test.

FsCheck generally assumes that the values it generates won't be mutated by the test itself - however when the test does not fail and so does not shrink you can pretty much get away with it, as internally FsCheck generates say an immutable list and then creates a new instance of the mutable `List` for every new test.

But for shrinking it assumes that the last value it generated is the one that failed the test and that it is supposed to shrink - but of course if that value gets changed by the test itself, in particular by making it bigger again, an infinite loop follows.

Here the sequence is something like:
- generate `[null], ""` (value is different from element of values)
- predicate fails because `[null, ""].First() != ""`
- try to shrink `[null,""]` to `[null]` (which is a shorter sublist of the original). Note that `[null,""]` was never generated, only `[null]` was, but because of the side-effecting `Add` that's what FsCheck thinks was generated.
- we're now back to step 1 because FsCheck runs the test with `[null], ""` as arguments.

You can avoid this problem by cloning the mutable list at the beginning of your test, e.g.

```csharp
values = new List<string>(values)
```

**Comment by tknightnd** [comment]
Great, I can work with that. Thanks for the quick reply Kurt. 

Closing the issue.
