### ISSUE TITLE
`Classify`, `Trivial`, `Label` not working in C#

### ISSUE THREAD

**Issue by t-hart** [fscheck/FsCheck#508]
# Problem

I've been using the FsCheck.Xunit package quite a bit recently---mostly with F#, but now also a little bit with C#---and while I've been able to make labels work in F#, I can't seem to make them (or any other console output) work in C#. I've tried both using the `Classify` function as described in (the docs)[https://fscheck.github.io/FsCheck/Properties.html], as well as the various methods, `Trivial`, `Label`, `Collect`, described in (this blog post)[https://www.codit.eu/blog/property-based-testing-with-c/].

Is there a trick to making it work that I'm missing?

Here's a basic example:
```cs
        [Property]
        public Property F(int x, int y) => (x + y == x + y).Trivial(x >= 0);
```

# Motivation

The motivation behind using these properties right now is inspecting the input. My coworker found out that overwriting the `ToString` method on the input objects lets you customize the output, but sometimes you might want to only inspect aspects of it. I'll open another issue on this if you want me to, but is there a way to only output text when a test fails or otherwise customize the input shown by FsCheck for a failing test?

**Comment by kurtschelfthout** [comment]
I’ll look at why there is no output from Trivial etc tonight, but as for your second question: there is an argument to Property called QuietOnSuccess which if you set it to true only prints if the test fails.

**Comment by kurtschelfthout** [comment]
So I'm not sure what the problem is, from my perspective it looks like all is working fine. For example, with your example literally pasted into an existing test project, I got:

```
Ok, passed 100 tests (58% trivial).
```

Was there anything else you were expecting?

`Label` and co, besides overriding `ToString` are definitely the right thing to look at in terms of customizing FsCheck's output. 

Keep the following in mind though:
- `Classify`, `Trivial` and `Collect` are intended to observe test case distribution, and as such are printed _only when the test succeeds_. FsCheck assumes that if the test fails, you have other things to worry about first.
- `Label` are intended to help diagnose failing tests, and as such are printed _only when the test fails_.

**Comment by t-hart** [comment]
Thanks for the quick reply and the troubleshooting. I don't know what's different between our setups, but I can't get it to work. To try and isolate it, I went and created a brand new test project via the `dotnet` command, added FsCheck.Xunit, and added the test pasted above. The test output I get does not mention the number of passed tests at all, nor what the trivial percentage is:
```
Starting test execution, please wait...

A total of 1 test files matched the specified pattern.

Test Run Successful.
Total tests: 1
     Passed: 1
 Total time: 2.6383 Seconds
```

And just for completeness, here's the entire class, the only source file in the project: 
```csharp
using FsCheck;
using FsCheck.Xunit;

namespace fscheck_test
{
    public class UnitTest1
    {
        [Property]
        public Property F(int x, int y) => (x + y == x + y).Trivial(x >= 0);
    }
}
```

Don't know if it matters, but I'm on macOS, running .NET version 3.0.100, though I'm pretty sure this was an issue even before updating yesterday.

Thanks for the tip about `QuietOnSuccess` too. I'm not sure what I'd use it with, though. Does it go with `Classify` and friends in the event that you don't want to see the output after all?

**Comment by t-hart** [comment]
However, this works, though it is more verbose:
```csharp
        [Fact]
        public void F() => Prop.ForAll<int, int>((x, y) => (x + y == x + y).Trivial(x >= 0)).QuickCheckThrowOnFailure();
```

```
Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
Ok, passed 100 tests (47% trivial).

Test Run Successful.
Total tests: 1
     Passed: 1
 Total time: 1.4901 Seconds
```

Can you not use the `[Property]` attribute for C# if you want output? It seems to run as expected otherwise, shrinking test inputs if something goes wrong, etc.

**Comment by kurtschelfthout** [comment]
I mentioned QuietOnSuccess since you asked “is there a way to not print anything if the test passes”...perhaps misunderstood the question. 

It’s odd it doesn’t print anything - I think it just may be something to do with how the dotnet test runner and xunit and fscheck.xunit deals with test output. Seems to work in .net framework which is what I tried yesterday - I’ll check dotnet core also   tonight.

**Comment by t-hart** [comment]
Ah, no, sorry, I think I just wasn't clear on formulating the follow-up. Since it silences output iff the test is successful, I didn't see when you would use it, but reading the section ['Running Tests'](https://fscheck.github.io/FsCheck/RunningTests.html#Using-FsCheck-Xunit-with-TestDriven-Net) cleared it up a bit.

And yeah, it's .net core, so that might be it. Thanks again for all your help.

**Comment by kurtschelfthout** [comment]
Sorry for the late reply here. It took a bit of digging. From my testing though, neither using `Fact` or `Property` produces test output _to the console_ using dotnet test. From what I've been able to piece together, this is either by design, an interaction between dotnet test and Xunit, or a bug in dotnet test. There seems to be a web of related issues on xunit, vstest and dotnet-cli, here's one entry point if you're inclined to dig deeper: https://github.com/microsoft/vstest/issues/799

See here how Xunit enforces you do test output: https://xunit.net/docs/capturing-output and if you care to look at FsCheck.Xunit, our `PropertyTestCase` does write the output to xunit's `TestOutputHelper`, which from that document I believe is the right thing to do for FsCheck.

Also, if you run `dotnet test --logger trx` then you'll get a trx file in TestResults folder, where you'll find the output, e.g.:

```
    <UnitTestResult executionId="1360b960-209a-4fd0-a397-b03863b6d919" testId="badc6589-1400-cf11-9a5b-b59df132c469" testName="fscheck_test.UnitTest1.F" computerName="SPJ" duration="00:00:00.1890000" startTime="2019-10-05T22:28:18.4012006+01:00" endTime="2019-10-05T22:28:18.4012085+01:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="1360b960-209a-4fd0-a397-b03863b6d919">
      <Output>
        <StdOut>Ok, passed 100 tests (54% trivial).</StdOut>
      </Output>
    </UnitTestResult>
```

I'm not sure there is anything to do for us here, sorry...feel free to point me in some direction if you disagree or know better!

**Comment by t-hart** [comment]
No worries! I've skimmed the thread, and as is mentioned,`Console.WriteLine` does appear to create output, both for `Fact` and for `Property` tests on macOS. That said, the issue with FsCheck's functions not logging I can't seem to solve for the console.

Using `--logger trx` outputs it to a file which contains the output I want, but I've not been able to get the same information out to the console, even after playing with verbosity levels.

I had a look at the `PropertyTestCase` type too, but I'm not entirely sure what I'm looking for. Is this it? 

```fs
// ...
 match xunitRunner.Result with
                          | TestResult.True _ ->
                            let output = Runner.onFinishedToString "" xunitRunner.Result
                            outputHelper.WriteLine(output)
                            new TestPassed(test, timer.Total, outputHelper.Output) :> TestResultMessage
// ...
```

From what I understand, it seems like the output goes written to the outputHelper, which gets passed to the TestPassed constructor, so that makes sense to me.

Anyway, is there a way to make the `ITestOutputHelper` work with `Trivial` and friends? From what you say, it seems you can, but I'm not sure how you'd do it. Do you have an example?

And I'm afraid I don't really have any other ideas as to where to go, so feel free to close the issue. Thanks again.

**Comment by kurtschelfthout** [comment]
> I've skimmed the thread, and as is mentioned,Console.WriteLine does appear to create output, both for Fact and for Property tests on macOS.

Ah yes - I'm on Windows, that explains why you're seeing output using `Fact` while I'm not. So the situation is:

- `Fact` and `QuickCheckThrowOnFailure` output to the console on Linux/Mac because they write to the console directly - but due to the vstest bug/feature/misfeature mentioned above even that doesn't log on Windows.
- `Property` follows xUnit's advice and writes to their `ITestOutputHelper`. FsCheck must do that, or there are other problems...e.g. in some test runners otherwise it has no clue which output to associate with which test if we write to console directly. 

Again I'm not entirely sure how a change to FsCheck can solve the conundrum. The best I can think of is to add a flag to FsCheck.Xunit's `PropertyAttribute` which sends output to console, instead of the outputhelper, but that's a really bad hack.

Can you try running:

```
dotnet test --logger:"console;verbosity=detailed"
```

Which prints perhaps more than what you want, but at least on my machine it definitely includes the messages from `Trival` etc.

**Comment by t-hart** [comment]
Huh, you're right. 
Using that command, I get the output that I'd expect from FsCheck. 

```
dotnet test --logger:"console;verbosity=detailed"
```

I was surprised that the output is so different from 
```
dotnet test --logger console --verbosity detailed
```

I had expected them to be the same.

But anyway, I think you're right in that adding hacks to get around this probably isn't the best idea. It's not blocking us in any way, so if using the above command is what we need to get FsCheck output, we'll just live with it for now :) 

Anyway, I think that's as far as we're gonna get on this issue. Let's hope that the platforms at least start behaving the same in the future, and that maybe we'll find an easier way to get the output later.
