### ISSUE TITLE
Metadata issue in 2.14.1

### ISSUE THREAD

**Issue by jbeeko** [fscheck/FsCheck#512]
There seems to be an issue with the Manifest of the nugget assemble for 2.14.1. After updating the paket lock file from 2.14 to 2.14.1 I am able to build fine but when running Expecto tests the tests fail with the following errors: 

```
[09:23:40 ERR] MyTestName errored in 00:00:00 <Expecto>
570System.IO.FileLoadException: Could not load file or assembly 'FsCheck, Version=2.14.0.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)...
```

Then executed the following:
`git clean -xfd` 
`paket clear-cache`
`paket -clear-cach --clear-local`
`botnet restore`

Build and ran tests, same result. I can see that version `2.14.1` is being downloaded from nugget.org. I also check the solution for any reference to 2.14, there is none. 

## Work around
Reverting paket.lock to 2.14 fixes the issue

**Comment by kurtschelfthout** [comment]
Doubt FsCheck is the issue here, as you can see it's unsigned so essentially the runtime shouldn't care about its version. It's more likely that a dependency of FsCheck is failing to load and there are different versions of e.g. FSharp.Core  in play - you may need to add assembly redirects. Another possibility is that Expecto is somehow doing something fishy, like loading assemblies manually.

Hard to tell you more without a repro.

**Comment by jbeeko** [comment]
Hum, I'll explore a bit more and reopen the case if I can create a clean repro.

**Comment by kurtschelfthout** [comment]
Ok. You’re welcome to keep this issue open for follow up if you like.

**Comment by kurtschelfthout** [comment]
Fyi this has been reported again separately with a repro this time, you may want to follow along:

https://github.com/fscheck/FsCheck/issues/512
