### ISSUE TITLE
Using `StdGen` in `Gen.eval` never varies in a loop

### ISSUE THREAD

**Issue by dharmaturtle** [fscheck/FsCheck#520]
Hi!

The following test prints out the same value 100 times.

```fsharp
[<Property(MaxTest = 1)>]
let ``Prints one hundred of the same value in a row``(gen: Random.StdGen): unit =
    let oneOrTwo = Gen.elements [1;2]
    for _ in [1..100] do
        oneOrTwo |> Gen.eval 1337 gen |> printfn "%i"
```

I find this surprising, as I would have assumed that it would have printed out 50/50 ratio of 1 and 2. What's the best way to accomplish this, assuming that `MaxTest` must be a small number like 1? I'm assuming that asking for `Random.StdGen` is incorrect, so what is the correct behavior? Currently my workaround is the following:

```fsharp
[<Property(MaxTest = 1)>]
let ``Works``(seed: int): unit =
    let size = 1_000_000_000
    let mutable seed = seed |> int64
    for _ in [1..100] do
        let gen = Random.mkStdGen seed
        Gen.elements [1;2] |> Gen.eval size gen |> printfn "%i"
        seed <- Arb.generate<int> |> Gen.eval size gen |> int64
        printfn "seed: %i" seed
```

**Comment by bender2k14** [comment]
May this how FsCheck implements these `Gen` types? ;)
![getRandomNumberReturns4](https://imgs.xkcd.com/comics/random_number.png)

In all seriousness, the answer is [mu](https://en.wikipedia.org/wiki/Mu_(negative)) (as I believe [Mark Seemann would say](https://blog.ploeh.dk/2019/02/04/how-to-get-the-value-out-of-the-monad/)).  Elaborating a bit, my understanding of this is something like "No, you are doing it wrong".

I am more familiar with [Hedgehog](https://github.com/hedgehogqa/fsharp-hedgehog) than FsCheck, but the same ideas should apply.  I have never seen a test using Hedgehog that uses a concept like `Gen.eval`.  This function appears to "get the value out of your moand".  Mu...no, don't do that.  Instead, I expect to see a computational expression in which you bind in input of `Gen.eval` to an identifier using `let!`.

More holistically,
1. generate all your random values first (which is fundamentally impure), then
2. use them to test your code (which is hopefully pure), and finally
3. assert that the final state of things is correct (which I think of as being impure since the behavior of this part of the test most directly affects the displayed result of the test).

So a randomized test is an [impureim sandwich](https://blog.ploeh.dk/2020/03/02/impureim-sandwich/).

In your case, don't try to generate 100 random values one at a time.  Instead, generate 100 random values all at once.  If the underlying type was`bool`, then this can be accomplished in Hedgehog with
```
Gen.bool |> Gen.list (Range.constant 100 100)
```

**Comment by dharmaturtle** [comment]
Classic [XY problem](https://en.wikipedia.org/wiki/XY_problem). Thanks  @bender2k14 :)

**Comment by bender2k14** [comment]
That looks much better.  Great job @dharmaturtle :)
