### ISSUE TITLE
Model as a list of values

### ISSUE THREAD

**Issue by Hugzy** [fscheck/FsCheck#524]
Hello,

I am currently attempting to use FsChecks model-based testing capabilities to test some REST APIs however I've run into an issue. I am using the experimental API from C# with NUnit.
When I use a list of values as my model like `List<int>`  the framework will generate lots of `create` commands populating the list as per my configuration. However, when `Check` is then called the entire list is passed in and I have no way of checking the state of the list as it was when each individual call to `Run` was made.

Using an example, let's say 5 calls to create where made and in each call, I take the last value and increment by 1 so my model after the 5 calls to `Run` looks like this

`List<int> {0,1,2,3,4}`

When FsCheck then calls check 5 times the entire list `List<int> {0,1,2,3,4}` will be passed in all 5 times making it very cumbersome to check if the advancements made to the SUT is legal because the Model is much farther ahead every single time except for the last one. I would expect it to actually replay the list as it was looking after each call to `Run` rather than passing in the final list each time, but maybe I am misunderstanding something. I also tried with a simpler `Model` of just an `int` and in this case when 5 calls to `Run` is made and the model value ends up being 5, with each call to check the `Model` increments corresponding to the value it would have been after x amounts of calls to `Run` rather than just the final value.

I have a C# project here(https://github.com/Hugzy/CounterTest) where I showcase the difference that I mention, namely in `CounterSpecVNext.cs` and `CounterSpecVNextInt.cs` to change the spec used, go to `CounterTest.cs` and change the spec in the `Counter` method.

**Comment by kurtschelfthout** [comment]
The model value is basically assumed to be an immutable value - basically in model-based testing FsCheck first generates a sequence of operations, and it needs to run the models to take e.g. preconditions into account. So if your model is a mutable value at each stage it's going to be in the final state after all operations are applied. This also helps with shrinking etc

So try using `ImmutableList` instead of `List`, alternatively I think cloning the `List` in each `Run` method before modifying it should work too.

**Comment by Hugzy** [comment]
Changing my model from a `List` to an `ImmutableList` did solve my issues, thank you.
