### ISSUE TITLE
how would i test the locally generated docs?

### ISSUE THREAD

**Issue by snuup** [fscheck/FsCheck#538]
the stylesheet reference in the template (and in the generated index.html) points to

    <link type="text/css" rel="stylesheet" href="/FsCheck/content/style.css" />

the generated docs are in the 

     /FsCheck/output 

folder. how do you develop these docs? i mean, if i want to work on the f# / c# switch issue for instance, at which folder would i start an http server?

**Comment by kurtschelfthout** [comment]
Seems like another issue. There used to be a "KeepRunning" which is nice because it automatically re-runs just the scripts you edit. But I think I didn't take it after the last Fake upgrade (they changed a whole bunch of API and I guess I got tired of it...)

I'll take another look at it. But yes the generated docs seems to only work when they are uploaded.

**Comment by kurtschelfthout** [comment]
Pending that, there should be a folder `docs/output` you can use? See https://github.com/fscheck/FsCheck/blob/master/build.fsx#L379 that's what is copied into the gh-pages branch which is what the docs points to: https://github.com/fscheck/FsCheck/tree/gh-pages

**Comment by snuup** [comment]
That was the first I tried, but that cannot work, because the paths in the html refer to "/FsCheck/..."

    <link type="text/css" rel="stylesheet" href="/FsCheck/content/style.css" />
    <script type="text/javascript" src="/FsCheck/content/tips.js"></script>

So before tweaking the docs (like the c#/f#) switch we must make them dev-able. I suggest we rename this issue to something like "Make Docs locally working for development purposes"

**Comment by kurtschelfthout** [comment]
Yes. It looks like things have moved on a bit https://fsprojects.github.io/FSharp.Formatting/upgrade.html

**Comment by kurtschelfthout** [comment]
Hmm...to get the build to work I have to update, but everything changed in F# Formatting. This will take a while...on the plus side it looks like there is some better options now for customization and styling: https://fsprojects.github.io/FSharp.Formatting/styling.html

**Comment by kurtschelfthout** [comment]
By way of update, I'm still looking at this. The latest version of F# Formatting has a feature so you can run in 'watch' mode which makes this pretty easy, but I need to make some changes to update to it.

**Comment by snuup** [comment]
Thank you for the update Kurt. Upgrading F# Formatting is certainly nice and make it simpler for contributors.

Once I find the time I will try to add coloring or toggling of c#/f# sample code. For that I will come along well with the current repo, I will easily hack the paths locally for development.

**Comment by kurtschelfthout** [comment]
I've released the new docs now with the new tooling, and updated the readme. Things have changed quite a bit so hopefully you can update what you have already to the new fsdocs version.

In direct response to your question there is now a `build -t WatchDocs` target which allows you to develop the docs locally easily. (You have to run just `build` first to get all deps and build once, I didn't add a dependency on the `Build` target for `WatchDocs` because it makes everything much slower)

**Comment by snuup** [comment]
this project is excellent maintained, thank you so much. i will certainly come along, otherwise let you know. working with latest f# formatting is very nice, thx.
