### ISSUE TITLE
Checking async method throws exception.

### ISSUE THREAD

**Issue by voroninp** [fscheck/FsCheck#579]
I cannot find (even FsCheck v.3) any option like `Prop.throws` to define that property throws exception asynchronously.

Am I missing anything?

**Comment by kurtschelfthout** [comment]
That's right. I'm inclined to leave that sort of stuff to assertion libraries (there are plenty of those).

Meanwhile it's probably relatively straightforward to wait for the Task to finish synchronously, if you really want to use `Prop.throws`.

**Comment by voroninp** [comment]
> That's right. I'm inclined to leave that sort of stuff to assertion libraries (there are plenty of those).

I might be not getting it 100%. Do you mean no support at all, or is there any way to combine async assertions with FsCheck's `Property`?

> Meanwhile it's probably relatively straightforward to wait for the Task to finish synchronously.

Yes, that's how I did.

**Comment by kurtschelfthout** [comment]
FsCheck 3 has support to check async methods, but I've been reluctant to add or extend assert functionality like `throws` because there are already so many libraries for that out that that specialize in that.

FsCheck derives whether a test passes or fails automatically based on the return type - if it runs without throwing an exception, the test passes, if it returns false or throws an exception, the test fails. This works well with assertion libraries because they'll throw with a useful error message if the assertion fails.

So if you find or already use some assert library that can do what you want you should be able to use that with FsCheck. Here's an example for NUnit: https://stackoverflow.com/questions/27024623/nunit3-assert-throws-with-async-task (I don't use that personally, just what came up in a search)
