### ISSUE TITLE
How to generate instances of more complicated data structures

### ISSUE THREAD

**Issue by edyoung** [fscheck/FsCheck#641]
Hi,

I'm new to FsCheck (awesome project!). This is a request for guidance rather than a bug report. I would like to test a C# API which takes as input objects with many fields, some of which are other nested objects, and use FsCheck to generate different inputs. This is using 3.0 RC1.

I have this so far, which appears to work but is a bit cumbersome, and would be worse with more properties. How can this be written more cleanly?

```C#
namespace PropTests
{
    public class T
    {
        public int X { get; set; }
        public string Y { get; set; }
        public T? Next { get; set; }
    }


    [TestClass]
    public class UnitTest1
    {        
        [TestMethod]
        public void TestMethod2()
        {
            ArbMap.Default.Merge<MyArbitraries>();
            var samples = Gen.Sample<T>(new ArbitraryT().Generator,100,100);                           
        }
    }

    public class ArbitraryT : Arbitrary<T>
    {
        public static Gen<T> SafeTHelper(int size)
        {
            var pairGen = ArbMap.Default.GeneratorFor<int>().Zip(ArbMap.Default.GeneratorFor<string>());
            if (size == 0)
            {
                return pairGen.Select(i => new T() { X = i.Item1, Y = i.Item2 });
            }
            else
            {
                var subtree = SafeTHelper(size / 2);
                return Gen.OneOf(
                    pairGen.Select(i => new T() { X = i.Item1, Y = i.Item2 }),
                    pairGen.Zip(subtree).Select(i => new T() { X = i.Item1.Item1, Y = i.Item1.Item2, Next = i.Item2 }));                    
            }
        }

        public override Gen<T> Generator {
            get
            {
                return Gen.Sized(SafeTHelper);
            }
        }
    }

    public class MyArbitraries
    {
        public static Arbitrary<T> T { get; } = new ArbitraryT();
    }
}
```

**Comment by kurtschelfthout** [comment]
That's a very broad question, but a few tips:
- You can use `ArbMap.Default.GeneratorFor<(int, string)>` or more complicated types that FsCheck knows how to generate directly. There' sno need to build those up from scratch with `Zip` etc as you're doing.
- If there is an easy conversion back and forth between an object FsCheck can generate out of the box, and another one, consider using `Arb.Convert`
- Generally most methods are also extension methods, like `Sample`, this reads a bit better in C#. If there's one that doesn't exist and you'd like it, open an issue :)
- Try to work with `Arbitrary` directly, instead of going via generators. This isn't always possible. E.g. use `ArbMap.Default.ArbFor<T>`.
- This will work much better with the `Prop.ForAll` API you will use to write some actual tests.
- take into account that the result of `Merge` is a new type to `Arbitrary` map. This line: `ArbMap.Default.Merge<MyArbitraries>();` doesn't do anything, since you don't use the result.
- instead of generating your `T` type recursively, consider letting FsCheck generate a list of random length, and then linking those together.

**Comment by bartelink** [comment]
@edyiung can you share where you landed on this and/or close it please? Kurt's advice is excellent, but I'm not sure this is an actionable issue as it stands, and such issues are a both a tax on the maintainer, and other users.

**Comment by edyoung** [comment]
I intended it as a discussion rather than an issue
