### ISSUE TITLE
Modelbased testing?

### ISSUE THREAD

**Issue by mmcedora** [fscheck/FsCheck#648]
What is the status of the modelbased testing support. The main link in the menu to "https://fscheck.github.io/FsCheck//StatefulTesting.html" is dead and the comming vNext version is live but marked experimental?

**Comment by bartelink** [comment]
Now at https://fscheck.github.io/FsCheck/StatefulTestingNew.html ?
The docs are for V3, and there is a nuget version 3.0.0-rc.1
Not sure what branch V3 is built from, but if its simply a broken link, a PR to fix it would probably be welcomed
(I'm sure Kurt will be along in due course with an actual answer)

**Comment by kurtschelfthout** [comment]
It’s already fixed but need to deploy it. Will try to do so soon but very much otherwise occupied atmWill also remove the experimental from state based testing and clean up; it’s the one you should use in 3.0. On 16 Oct 2023, at 12:46, Ruben Bartelink ***@***.***> wrote:﻿
Now at https://fscheck.github.io/FsCheck/StatefulTestingNew.html ?
The docs are for V3, and there is a nuget version 3.0.0-rc.1
Not sure what branch V3 is built from, but if its simply a broken link, a PR to fix it would probably be welcomed
(I'm sure Kurt will be along in due course with an actual answer)

**Comment by kurtschelfthout** [comment]
now finally pushed
