### ISSUE TITLE
Packaging improvements

### ISSUE THREAD

**Issue by kurtschelfthout** [fscheck/FsCheck#664]
With the recent changes in deploy, I believe we are in a good position to modernize FsCheck packaging.

- [ ] Enable source linking
- [ ] Enable deterministic build
- [ ] Check if we can include compiler flags (not sure fsc does that)

Imo source linking is pretty useful. It used to be enabled but it bitrotted, I think it's much more standardized now.

Goal would be to have a squeky clean Nuget package explorer health check. Currently looks like this:

![image](https://github.com/fscheck/FsCheck/assets/164917/24e74e27-a432-4ac8-9592-49d07001f4eb)

**Comment by Smaug123** [comment]
I'm looking at sourcelink now. (I need to get round to it for my own packages anyway.)

**Comment by Smaug123** [comment]
To my great surprise, [there is no public way of reading SourceLink metadata](https://developercommunity.visualstudio.com/t/Is-there-an-API-for-reading-Source-Link-/1468642)?! (Maybe this is not to my surprise, because this is MsBuild we're talking about.

**Comment by Smaug123** [comment]
I'm not convinced that EmbedUntrackedSources is what we want (at least, I'm not convinced until I can know what those untracked sources *are*).

**Comment by Smaug123** [comment]
Before working out that mystery, I've pulled out https://github.com/fscheck/FsCheck/pull/670 for just the deterministic builds bit.

**Comment by Smaug123** [comment]
The compilation options thing is not supported in F# (https://github.com/dotnet/fsharp/issues/12002).

**Comment by Smaug123** [comment]
To summarise:

* Deterministic builds and SourceLink are now working (as you noted in https://github.com/fscheck/FsCheck/pull/670#issuecomment-1963022094), modulo [a bug in the F# compiler](https://github.com/dotnet/fsharp/issues/16768) and [a bug in the interaction between MsBuild and the compiler](https://github.com/dotnet/fsharp/issues/16771). 
* Compilation options [are not supported](https://github.com/dotnet/fsharp/issues/12002).

I think this ticket can be closed, because it's as complete as it's practical to be.
