### ISSUE TITLE
CVE issues from use of old libraries

### ISSUE THREAD

**Issue by kiljoy001** [fscheck/FsCheck#680]
![image](https://github.com/fscheck/FsCheck/assets/8892111/a21eef82-88bc-42fa-9bd3-8111e618ab59)
![image](https://github.com/fscheck/FsCheck/assets/8892111/00d13523-dc48-4ea1-ae82-8b533117c08d)
![image](https://github.com/fscheck/FsCheck/assets/8892111/81fae29b-2936-4889-bb60-952418d5f891)
![image](https://github.com/fscheck/FsCheck/assets/8892111/fdac2b74-d3c2-4c70-a3f9-3a5016dc46e2)
![image](https://github.com/fscheck/FsCheck/assets/8892111/9695e376-7103-49aa-a174-e5a078011d8a)
![image](https://github.com/fscheck/FsCheck/assets/8892111/437f3f5c-bf00-4679-b196-0e580f5301ce)
![image](https://github.com/fscheck/FsCheck/assets/8892111/b7efe2c5-9c43-4d15-a7a1-02ea6fd5795e)

These have been flagged by synk, not sure if they are fixable, but they are problematic and serious issues.

**Comment by bartelink** [comment]
https://www.nuget.org/packages/FsCheck/3.0.0-rc3#dependencies-body-tab
https://www.nuget.org/packages/FsCheck.xunit/3.0.0-rc3#dependencies-body-tab

Note that you'll end up in a world of pain if you go too far down this rabbit hole though - just because some random xunit assembly touches a net fw assembly does not mean your code does; test assemblies are not part of your deployed prod code attack surface

As such, they should not be included in these scans

Of course, if your actual app code references xunit/fscheck, then you've got bigger problems...

**Comment by kiljoy001** [comment]
I went ahead and updated to the release candidate, some issues remain, however:
![image](https://github.com/fscheck/FsCheck/assets/8892111/253c96c8-8de4-4196-89e0-af1404f766c6)
![image](https://github.com/fscheck/FsCheck/assets/8892111/ba18483a-4a4b-430e-a152-51be2f7bb900)
![image](https://github.com/fscheck/FsCheck/assets/8892111/e6389147-16ba-48f4-87bb-37d4462b396c)
![image](https://github.com/fscheck/FsCheck/assets/8892111/808753fe-9eae-4f8e-bb46-10b51aad1bb1)
![image](https://github.com/fscheck/FsCheck/assets/8892111/309c9104-f03c-4444-a9a9-6e7c91f851b9)
![image](https://github.com/fscheck/FsCheck/assets/8892111/d3105f6a-0458-4969-b8df-49005152d30f)
To be fair, I am not using the library directly in my project but as a testing framework, however, I think it is good to let you know that these issues exist.

**Comment by bartelink** [comment]
The point here though is that you're using FsCheck.Xunit, which is a library that you use to hook a property test into xunit via `Property`
you'll get identical results from using xunit itself directly via `Fact`

The bottom line here is that the fix is to exclude tests from the scanning as:
- some xunit assemblies have a transitive reference to something that might be bad
- xunit does not actually use those (go look in the xunit repo)

Once again: the real answer here is that you need to remove test assemblies from your scans.

There is no direct problem with FsCheck of any Kind

There is an indirect one in Xunit

But the real problem is that you are scanning non production assemblies for vulerabilities

**Comment by kurtschelfthout** [comment]
Closing as nothing to do here.
